// 城市定义，JS版，建议使用json
//阿克苏|AKeSu|AKeSu|AKS|AKU|中国|亚洲|China
var cities=[
{name:"阿布贾",info1:"Abuja",info2:"abujia",info3:"ABJ",info4:"ABV",info5:"尼日利亚",info6:"国际",info7:"Nigeria"},
{name:"阿伯丁",info1:"Aberdeen ",info2:"ABoDing",info3:"ABD",info4:"ABZ",info5:"英国",info6:"欧洲",info7:"UK"},
{name:"阿比让",info1:"Abidjan",info2:"abirang",info3:"ABR",info4:"ABJ",info5:"科特迪瓦",info6:"国际",info7:"Ivory Coast (Cote d'Ivoire)"},
{name:"阿德莱德",info1:"Adelaide",info2:"Adelaide",info3:"ADLD",info4:"ADL",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"阿克拉",info1:"Accra",info2:"akela",info3:"AKL",info4:"ACC",info5:"加纳",info6:"国际",info7:"Ghana"},
{name:"阿克苏",info1:"AKeSu",info2:"AKeSu",info3:"AKS",info4:"AKU",info5:"中国",info6:"亚洲",info7:"China"},
{name:"阿尔及尔",info1:"Algiers",info2:"aerjier",info3:"AEJE",info4:"ALG",info5:"阿尔及利亚",info6:"国际",info7:"Algeria"},
{name:"阿拉木图",info1:"Alma-Ata",info2:"ALaMuTu",info3:"almt",info4:"ALA",info5:"哈萨克斯坦",info6:"亚洲",info7:"Kazakhstan"},
{name:"阿勒泰",info1:"ALeTai",info2:"ALeTai",info3:"ALT",info4:"AAT",info5:"中国",info6:"亚洲",info7:"China"},
{name:"阿姆利则",info1:"Amritsar",info2:"amulize",info3:"AMLZ",info4:"ATQ",info5:"印度",info6:"亚洲",info7:"India"},
{name:"阿姆斯特丹",info1:"Amsterdam",info2:"AMuSiTeDan",info3:"amstd",info4:"AMS",info5:"荷兰",info6:"欧洲",info7:"Netherlands"},
{name:"阿皮亚",info1:"Apia",info2:"Apiya",info3:"APY",info4:"APW",info5:"西萨摩亚",info6:"大洋洲",info7:"Western Samoa"},
{name:"阿斯塔纳",info1:"Astana",info2:"ASiTaNa",info3:"ASTN",info4:"TSE",info5:"哈萨克斯坦",info6:"亚洲",info7:"Kazakhstan"},
{name:"阿什哈巴德",info1:"Ashkhabad",info2:"AShenHaBaDe",info3:"ashbd",info4:"ASB",info5:"土库曼斯坦",info6:"亚洲",info7:"Turkmenistan"},
{name:"爱丁堡",info1:"Edinburgh",info2:"AiDingBao",info3:"adb",info4:"EDI",info5:"苏格兰",info6:"欧洲",info7:"Scotland"},
{name:"爱德蒙顿",info1:"Edmonton",info2:"Aidemengdun",info3:"ADMD",info4:"YEG",info5:"加拿大",info6:"北美",info7:"Canada"},
{name:"埃默拉尔德",info1:"Emerald",info2:"Aimolaerde",info3:"AMLED",info4:"EMD",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"安康",info1:"AnKang",info2:"AnKang",info3:"AK",info4:"AKA",info5:"中国",info6:"亚洲",info7:"China"},
{name:"安庆",info1:"AnQing",info2:"AnQing",info3:"AQ",info4:"AQG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"安曼",info1:"Amman",info2:"anman",info3:"AM",info4:"AMM",info5:"约旦",info6:"亚洲",info7:"Jordan"},
{name:"鞍山",info1:"AnShan",info2:"AnShan",info3:"AS",info4:"AOG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"奥克兰",info1:"Auckland",info2:"Aokelan",info3:"AKL",info4:"AKL",info5:"新西兰",info6:"大洋洲",info7:"New Zealand"},
{name:"奥什",info1:"Osh",info2:"AoShen",info3:"as",info4:"OSS",info5:"吉尔吉斯斯坦",info6:"亚洲",info7:"Krygyzstan"},
{name:"奥兰多",info1:"Orlando",info2:"AoLanDuo",info3:"ald",info4:"MCO",info5:"美国",info6:"北美",info7:"USA"},
{name:"奥斯陆",info1:"Oslo",info2:"Aosilu",info3:"OSL",info4:"OSL",info5:"挪威",info6:"欧洲",info7:"Norway"},
{name:"澳门",info1:"Macau",info2:"AoMen",info3:"AM",info4:"MFM",info5:"中国",info6:"亚洲",info7:"ChinaLand"},
{name:"巴库",info1:"Baku",info2:"BaKu",info3:"bk",info4:"BAK",info5:"阿塞拜疆",info6:"欧洲",info7:"Azerbaijan"},
{name:"巴黎",info1:"Paris",info2:"BaLi",info3:"bl",info4:"PAR",info5:"法国",info6:"欧洲",info7:"France"},
{name:"巴厘岛",info1:"Denpasar Bali",info2:"balidao",info3:"BLD",info4:"DPS",info5:"印度尼西亚",info6:"亚洲",info7:"Indonesia"},
{name:"巴林",info1:"Bahrain",info2:"balin",info3:"BL",info4:"BAH",info5:"巴林",info6:"亚洲",info7:"Bahrain"},
{name:"巴邻旁",info1:"Palembang",info2:"balinpang",info3:"BLP",info4:"PLM",info5:"印度尼西亚",info6:"亚洲",info7:"Indonesia"},
{name:"巴特那",info1:"Patna",info2:"batena",info3:"BTN",info4:"PAT",info5:"印度",info6:"亚洲",info7:"India"},
{name:"巴伦西亚",info1:"Valencia",info2:"balunxiya",info3:"BLXY",info4:"VLC",info5:"西班牙",info6:"欧洲",info7:"Spain"},
{name:"巴塞罗那",info1:"Barcelona",info2:"BaSaiLuoNa",info3:"bsln",info4:"BCN",info5:"西班牙",info6:"欧洲",info7:"Spain"},
{name:"保山",info1:"BaoShan",info2:"BaoShan",info3:"BS",info4:"BSD",info5:"中国",info6:"亚洲",info7:"China"},
{name:"包头",info1:"BaoTou",info2:"BaoTou",info3:"BT",info4:"BAV",info5:"中国",info6:"亚洲",info7:"China"},
{name:"白山",info1:"BaiShan",info2:"BaiShan",info3:"BS",info4:"NBS",info5:"中国",info6:"亚洲",info7:"China"},
{name:"北京",info1:"BeiJing",info2:"BeiJing",info3:"BJ",info4:"PEK",info5:"中国",info6:"亚洲",info7:"China"},
{name:"北海",info1:"BeiHai",info2:"BeiHai",info3:"BH",info4:"BHY",info5:"中国",info6:"亚洲",info7:"China"},
{name:"班加罗尔",info1:"Bengaluru",info2:"banjiailuoer",info3:"BJLE",info4:"BLR",info5:"印度",info6:"亚洲",info7:"India"},
{name:"班达伯格",info1:"Bundaberg",info2:"Bandaboge",info3:"BDBG",info4:"BDB",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"贝尔法斯特",info1:"Belfast ",info2:"BeiErFaSiTe",info3:"BEFST",info4:"BFS",info5:"爱尔兰",info6:"欧洲",info7:"Ireland"},
{name:"贝尔格莱德",info1:"Belgrade",info2:"beiergelaide",info3:"BEGLD",info4:"BEG",info5:"塞尔维亚",info6:"欧洲",info7:"Serbia"},
{name:"贝鲁特",info1:"Beirut",info2:"beilute",info3:"BLT",info4:"BEY",info5:"黎巴嫩",info6:"亚洲",info7:"Lebanon"},
{name:"比萨",info1:"Pisa",info2:"bisa",info3:"BS",info4:"PSA",info5:"意大利",info6:"欧洲",info7:"Italy"},
{name:"比什凯克",info1:"Bishkek",info2:"BiShenKaiKe",info3:"bskk",info4:"FRU",info5:"吉尔吉斯斯坦",info6:"亚洲",info7:"Kyrgyz"},
{name:"毕节",info1:"BiJie ",info2:"BiJie",info3:"BJ",info4:"BFJ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"北九州",info1:"Kitakyushu",info2:"BeiJiuZhou",info3:"bjz",info4:"KKJ",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"槟城",info1:"Penang",info2:"BinCheng",info3:"bc",info4:"PEN",info5:"马来群岛",info6:"亚洲",info7:"Malaysia"},
{name:"波尔图",info1:"Porto",info2:"boertu",info3:"BET",info4:"OPO",info5:"葡萄牙",info6:"欧洲",info7:"Portugal"},
{name:"伯明翰",info1:"Birmingham",info2:"BoMingHan",info3:"bmh",info4:"BHX",info5:"英国",info6:"欧洲",info7:"UK"},
{name:"博乐",info1:"Bole",info2:"Bole",info3:"BL",info4:"BPL",info5:"中国",info6:"亚洲",info7:"China"},
{name:"博洛尼亚",info1:"Bologna",info2:"boluoniya",info3:"BLNY",info4:"BLQ",info5:"意大利",info6:"欧洲",info7:"Italy"},
{name:"柏林",info1:"Berlin",info2:"BoLin",info3:"bl",info4:"BER",info5:"德国",info6:"欧洲",info7:"Germany"},
{name:"波特兰",info1:"Portland",info2:"Botelan",info3:"BTL",info4:"PDX",info5:"美国",info6:"北美",info7:"United States"},
{name:"波士顿",info1:"Boston",info2:"BoShiDun",info3:"bsd",info4:"BOS",info5:"美国",info6:"北美",info7:"USA"},
{name:"布拉格",info1:"Prague",info2:"bulage",info3:"BLG",info4:"PRG",info5:"捷克",info6:"欧洲",info7:"Czech Republic"},
{name:"布鲁塞尔",info1:"Brussels",info2:"BuLuSaiEr",info3:"blse",info4:"BRU",info5:"比利时",info6:"欧洲",info7:"Belgium"},
{name:"长白山",info1:"ChangBaiShan",info2:"ChangBaiShan",info3:"CBS",info4:"NBS",info5:"中国",info6:"亚洲",info7:"China"},
{name:"昌迪加尔",info1:"Chandigarh",info2:"changdijiaer",info3:"CDJE",info4:"IXC",info5:"印度",info6:"亚洲",info7:"India"},
{name:"昌都",info1:"ChangDu",info2:"ChangDu",info3:"CD",info4:"BPX",info5:"中国",info6:"亚洲",info7:"China"},
{name:"长春",info1:"ChangChun",info2:"ChangChun",info3:"CC",info4:"CGQ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"常德",info1:"ChangDe",info2:"ChangDe",info3:"CD",info4:"CGD",info5:"中国",info6:"亚洲",info7:"China"},
{name:"长崎",info1:"Nagasaki",info2:"changqi",info3:"CQ",info4:"NGS",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"长沙",info1:"ChangSha",info2:"ChangSha",info3:"CS",info4:"CSX",info5:"中国",info6:"亚洲",info7:"China"},
{name:"长治",info1:"ChangZhi",info2:"ChangZhi",info3:"CZ",info4:"CIH",info5:"中国",info6:"亚洲",info7:"China"},
{name:"常州",info1:"ChangZhou",info2:"ChangZhou",info3:"CZ",info4:"CZX",info5:"中国",info6:"亚洲",info7:"China"},
{name:"朝阳",info1:"ZhaoYang",info2:"ZhaoYang",info3:"ZY",info4:"CHG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"成都",info1:"ChengDu",info2:"ChengDu",info3:"CD",info4:"CTU",info5:"中国",info6:"亚洲",info7:"China"},
{name:"赤峰",info1:"ChiFeng",info2:"ChiFeng",info3:"CF",info4:"CIF",info5:"中国",info6:"亚洲",info7:"China"},
{name:"重庆",info1:"ChongQing",info2:"ChongQing",info3:"CQ",info4:"CKG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"冲绳",info1:"Okinawa",info2:"chongsheng",info3:"CS",info4:"OKA",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"大阪",info1:"Osaka",info2:"DaBan",info3:"db",info4:"KIX",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"大理",info1:"DaLi",info2:"DaLi",info3:"DL",info4:"DLU",info5:"中国",info6:"亚洲",info7:"China"},
{name:"大邱",info1:"Taegu",info2:"DaQiu",info3:"dq",info4:"TAE",info5:"韩国",info6:"亚洲",info7:"SouthKorea"},
{name:"达卡",info1:"Dhaka",info2:"Daka",info3:"DK",info4:"DAC",info5:"孟加拉国",info6:"亚洲",info7:"Bangladesh"},
{name:"达喀尔",info1:"Dakar",info2:"dakaer",info3:"DKE",info4:"DKR",info5:"塞内加尔",info6:"国际",info7:"Senegal"},
{name:"达拉斯--奥斯堡",info1:"Dallas/Fort Worth",info2:"Dalasiaosibao",info3:"DLSASB",info4:"DFW",info5:"美国",info6:"北美",info7:"United States"},
{name:"达累斯萨拉姆",info1:"Dar Es Salaam",info2:"daleisisalamu",info3:"DLSSLM",info4:"DAR",info5:"坦桑尼亚",info6:"国际",info7:"Tanzania"},
{name:"大连",info1:"DaLian",info2:"DaLian",info3:"DL",info4:"DLC",info5:"中国",info6:"亚洲",info7:"China"},
{name:"大庆",info1:"DaQing",info2:"DaQing",info3:"DQ",info4:"DQA",info5:"中国",info6:"亚洲",info7:"China"},
{name:"大同",info1:"DaTong",info2:"DaTong",info3:"DT",info4:"DAT",info5:"中国",info6:"亚洲",info7:"China"},
{name:"丹东",info1:"DanDong",info2:"DanDong",info3:"DD",info4:"DDG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"丹佛",info1:"Denver",info2:"Danfo",info3:"DF",info4:"DEN",info5:"美国",info6:"北美",info7:"United States"},
{name:"旦尼丁",info1:"Dunedin",info2:"Danniding",info3:"DND",info4:"DUD",info5:"新西兰",info6:"大洋洲",info7:"New Zealand"},
{name:"达曼",info1:"Dammam",info2:"daman",info3:"DM",info4:"DMM",info5:"沙竺阿拉伯",info6:"亚洲",info7:"Saudi Arabia"},
{name:"达县",info1:"DaXian",info2:"DaXian",info3:"DX",info4:"DAX",info5:"中国",info6:"亚洲",info7:"China"},
{name:"德班",info1:"Durban",info2:"deban",info3:"DB",info4:"DUR",info5:"南非",info6:"国际",info7:"South Africa"},
{name:"德里",info1:"Delhi",info2:"DeLi",info3:"dl",info4:"DEL",info5:"印度",info6:"亚洲",info7:"India"},
{name:"德阳",info1:"Deyang",info2:"DeYang",info3:"DY",info4:"DEY",info5:"中国",info6:"亚洲",info7:"China"},
{name:"德宏芒市",info1:"DeHongMangShi",info2:"DeHongMangShi",info3:"DHMS",info4:"LUM",info5:"中国",info6:"亚洲",info7:"China"},
{name:"德黑兰",info1:"Teheran",info2:"DeHeiLan",info3:"dhl",info4:"IKA",info5:"伊朗",info6:"亚洲",info7:"Iran"},
{name:"迪拜",info1:"Dubai",info2:"DiBai",info3:"db",info4:"DXB",info5:"阿拉伯联合酋长国",info6:"亚洲",info7:"UnitedArabEmirates"},
{name:"迪庆",info1:"DiQing",info2:"DiQing",info3:"DQ",info4:"DIG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"第比利斯",info1:"Tbilisi",info2:"dibilisi",info3:"DBLS",info4:"TBS",info5:"格鲁吉亚",info6:"欧洲",info7:"Georgia"},
{name:"底特律",info1:"Detroit",info2:"Detelv",info3:"DTL",info4:"DTT",info5:"美国",info6:"北美",info7:"United States"},
{name:"东加大埔",info1:"Tongatapu, Tonga Isl",info2:"Dongjiadafu",info3:"DJDF",info4:"TBU",info5:"汤加",info6:"大洋洲",info7:"Tonga"},
{name:"东莞",info1:"Dongguan",info2:"Dongguan",info3:"DG",info4:"DDB",info5:"中国",info6:"亚洲",info7:"China"},
{name:"东京",info1:"Tokyo",info2:"DongJing",info3:"dj",info4:"NRT",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"东营",info1:"DongYing",info2:"DongYing",info3:"DY",info4:"DOY",info5:"中国",info6:"亚洲",info7:"China"},
{name:"敦煌",info1:"DunHuang",info2:"DunHuang",info3:"DH",info4:"DNH",info5:"中国",info6:"亚洲",info7:"China"},
{name:"都柏林",info1:"Dublin",info2:"dubolin",info3:"DBL",info4:"DUB",info5:"爱尔兰",info6:"欧洲",info7:"Ireland"},
{name:"多伦多",info1:"Toronto",info2:"Duolunduo",info3:"DLD",info4:"YTO",info5:"加拿大",info6:"北美",info7:"Canada"},
{name:"杜尚别",info1:"Dushanbe",info2:"DuShangBie",info3:"dsb",info4:"DYU",info5:"塔吉克斯坦",info6:"亚洲",info7:"Tajikistan"},
{name:"杜阿拉",info1:"Douala",info2:"duala",info3:"DAL",info4:"DLA",info5:"喀麦隆",info6:"国际",info7:"Cameroon"},
{name:"杜塞尔多夫",info1:"Dusseldorf",info2:"DuSaiErDuoFu",info3:"dsedf",info4:"DUS",info5:"德国",info6:"欧洲",info7:"Germany"},
{name:"多哈",info1:"Doha",info2:"duoha",info3:"DH",info4:"DOH",info5:"卡塔尔",info6:"亚洲",info7:"Qatar"},
{name:"恩德培",info1:"Entebbe/Kampala",info2:"endepei",info3:"EDP",info4:"EBB",info5:"乌干达",info6:"国际",info7:"Uganda"},
{name:"恩施",info1:"EnShi",info2:"EnShi",info3:"ES",info4:"ENH",info5:"中国",info6:"亚洲",info7:"China"},
{name:"鄂尔多斯",info1:"EErDuoSi",info2:"EErDuoSi",info3:"EEDS",info4:"DSN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"法兰克福",info1:"Frankfurt",info2:"FaLanKeFu",info3:"flkf",info4:"FRA",info5:"德国",info6:"欧洲",info7:"Germany"},
{name:"费城",info1:"Philadelphia",info2:"Feicheng",info3:"FC",info4:"PHL",info5:"美国",info6:"北美",info7:"United States"},
{name:"佛山",info1:"Foshan",info2:"Foshan",info3:"FS",info4:"FSA",info5:"中国",info6:"亚洲",info7:"China"},
{name:"符拉迪沃斯托克",info1:"Vladivostok",info2:"FuLaDiWoSiTuoKe",info3:"fldwstk",info4:"VVO",info5:"俄罗斯",info6:"欧洲",info7:"Russia"},
{name:"福岛",info1:"Fukushima",info2:"fudao",info3:"FD",info4:"FKS",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"福冈",info1:"Fukuoka",info2:"FuGang",info3:"fg",info4:"FUK",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"福州",info1:"FuZhou",info2:"FuZhou",info3:"FZ",info4:"FOC",info5:"中国",info6:"亚洲",info7:"China"},
{name:"富山",info1:"Toyama",info2:"FuShan",info3:"fs",info4:"TOY",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"釜山",info1:"Pusan",info2:"FuShan",info3:"fs",info4:"PUS",info5:"韩国",info6:"亚洲",info7:"SouthKorea"},
{name:"阜阳",info1:"FuYang",info2:"FuYang",info3:"FY",info4:"FUG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"哥打基纳巴卢",info1:"KOTAKINABALU",info2:"GeDaJiNaBaLu",info3:"gdjnbl",info4:"BKI",info5:"马来西亚",info6:"亚洲",info7:"Malaysia"},
{name:"歌德堡",info1:"Goteborg",info2:"gedebao",info3:"GDB",info4:"GOT",info5:"瑞典",info6:"欧洲",info7:"Sweden"},
{name:"哥伦布",info1:"Columbus",info2:"Gelunbu",info3:"GLB",info4:"CMH",info5:"美国",info6:"北美",info7:"United States"},
{name:"哥本哈根",info1:"Copenhagen",info2:"GeBenHaGen",info3:"gbhg",info4:"CPH",info5:"丹麦",info6:"欧洲",info7:"Denmark"},
{name:"哥打巴鲁",info1:"Kota Bharu",info2:'gedabalu',info3:"GDBL",info4:"KBR",info5:"马来西亚",info6:"亚洲",info7:"Malaysia"},
{name:"古晋",info1:"Kuching",info2:'gujing',info3:"GJ",info4:"KCH",info5:"马来西亚",info6:"亚洲",info7:"Malaysia"},
{name:"光州",info1:"Kwangju",info2:"GuangZhou0",info3:"gz",info4:"KWJ",info5:"韩国",info6:"亚洲",info7:"SouthKorea"},
{name:"关岛",info1:"Guam",info2:"Guandao",info3:"GD",info4:"GUM",info5:"美国",info6:"北美",info7:"United States"},
{name:"关丹",info1:"Kuantan",info2:'guandan',info3:"GD",info4:"KUA",info5:"马来西亚",info6:"亚洲",info7:"Malaysia"},
{name:"瓜拉丁加奴",info1:"Kuala Terengganu",info2:'gualadingjianv',info3:"GLDJN",info4:"TGG",info5:"马来西亚",info6:"亚洲",info7:"Malaysia"},
{name:"广州",info1:"GuangZhou",info2:"GuangZhou",info3:"GZ",info4:"CAN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"广岛",info1:"Hiroshima",info2:"GuangDao",info3:"gd",info4:"HIJ",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"广元",info1:"GuangYuan",info2:"GuangYuan",info3:"GY",info4:"GYS",info5:"中国",info6:"亚洲",info7:"China"},
{name:"广汉",info1:"GuangHan",info2:"GuangHan",info3:"GH",info4:"GHN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"赣州",info1:"GanZhou",info2:"GanZhou",info3:"GZ",info4:"KOW",info5:"中国",info6:"亚洲",info7:"China"},
{name:"格尔木",info1:"GeErMu",info2:"GeErMu",info3:"GEM",info4:"GOQ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"格拉德斯通",info1:"Gladstone",info2:"Geladesitong",info3:"GLDST",info4:"GLT",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"格拉斯哥",info1:"Glasgow",info2:"GeLaSiGe",info3:"GLSG",info4:"GLA",info5:"英国",info6:"欧洲",info7:"UK"},
{name:"桂林",info1:"GuiLin",info2:"GuiLin",info3:"GL",info4:"KWL",info5:"中国",info6:"亚洲",info7:"China"},
{name:"贵阳",info1:"GuiYang",info2:"GuiYang",info3:"GY",info4:"KWE",info5:"中国",info6:"亚洲",info7:"China"},
{name:"哈尔滨",info1:"Harbin",info2:"HaErBin",info3:"HEB",info4:"HRB",info5:"中国",info6:"亚洲",info7:"China"},
{name:"哈巴罗夫斯克市",info1:"Khabarovsk",info2:"HaBaLuoFuSiKeShi",info3:"hblfsks",info4:"KHV",info5:"俄罗斯",info6:"欧洲",info7:"Russia"},
{name:"哈拉雷",info1:"Harare",info2:"halalei",info3:"HLL",info4:"HRE",info5:"津巴布韦",info6:"国际",info7:"Zimbabwe"},
{name:"哈密",info1:"HaMi",info2:"HaMi",info3:"HM",info4:"HMI",info5:"中国",info6:"亚洲",info7:"China"},
{name:"哈密尔顿",info1:"Hamilton",info2:"Hamierdun",info3:"HMED",info4:"HLZ",info5:"加拿大",info6:"北美",info7:"Canada"},
{name:"哈科特港",info1:"Port Harcourt",info2:"haketegang",info3:"HKTG",info4:"PHC",info5:"尼日利亚",info6:"国际",info7:"Nigeria"},
{name:"哈特福德",info1:"Hartford",info2:"HaTeFuDe",info3:"htfd",info4:"BDL",info5:"美国",info6:"北美",info7:"USA"},
{name:"海口",info1:"HaiKou",info2:"HaiKou",info3:"HK",info4:"HAK",info5:"中国",info6:"亚洲",info7:"China"},
{name:"海拉尔",info1:"HaiLaEr",info2:"HaiLaEr",info3:"HLE",info4:"HLD",info5:"中国",info6:"亚洲",info7:"China"},
{name:"海得拉巴",info1:"Hyderabad",info2:"haidelaba",info3:"HDLB",info4:"HYD",info5:"印度",info6:"亚洲",info7:"India"},
{name:"海参葳",info1:"Vladivostok",info2:"HaiShenWei",info3:"HSW",info4:"VVO",info5:"俄罗斯",info6:"欧洲",info7:"Russia"},
{name:"邯郸",info1:"HanDan",info2:"HanDan",info3:"HD",info4:"HDG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"汉中",info1:"HanZhong",info2:"HanZhong",info3:"HZ",info4:"HZG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"汉堡",info1:"Hamburg",info2:"HanBao",info3:"hb",info4:"HAM",info5:"德国",info6:"欧洲",info7:"Germany"},
{name:"汉密尔顿岛",info1:"Hamilton Island",info2:"Hanmierdundao",info3:"HMEDD",info4:"HTI",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"杭州",info1:"HangZhou",info2:"HangZhou",info3:"HZ",info4:"HGH",info5:"中国",info6:"亚洲",info7:"China"},
{name:"赫尔辛基",info1:"Helsinki",info2:"HeErXinJi",info3:"hexj",info4:"HEL",info5:"芬兰",info6:"欧洲",info7:"Finland"},
{name:"霍巴特",info1:"Hobart",info2:"Huobate",info3:"HBT",info4:"HBA",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"合肥",info1:"HeFei",info2:"HeFei",info3:"HF",info4:"HFE",info5:"中国",info6:"亚洲",info7:"China"},
{name:"和田",info1:"HeTian",info2:"HeTian",info3:"HT",info4:"HTN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"黑河",info1:"HeiHe",info2:"HeiHe",info3:"HH",info4:"HEK",info5:"中国",info6:"亚洲",info7:"China"},
{name:"河内",info1:"Hanoi",info2:"HeNei",info3:"hn",info4:"HAN",info5:"越南",info6:"亚洲",info7:"Vietnam"},
{name:"衡阳",info1:"HengYang",info2:"HengYang",info3:"HY",info4:"HNY",info5:"中国",info6:"亚洲",info7:"China"},
{name:"呼和浩特",info1:"HuHeHaoTe",info2:"HuHeHaoTe",info3:"HHHT",info4:"HET",info5:"中国",info6:"亚洲",info7:"China"},
{name:"华沙",info1:"Warsaw",info2:"HuaSha",info3:"hs",info4:"WAW",info5:"波兰",info6:"欧洲",info7:"Poland"},
{name:"华盛顿",info1:"Washington",info2:"Huashengdun",info3:"HSD",info4:"WAS",info5:"美国",info6:"北美",info7:"United States"},
{name:"怀化",info1:"HuaiHua",info2:"HuaiHua",info3:"HH",info4:"HJJ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"黄金海岸",info1:"Gold Coast",info2:"Huangjinhaian",info3:"HJHA",info4:"OOL",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"黄果树",info1:"HuangGuoShu",info2:"HuangGuoShu",info3:"HGS",info4:"AVA",info5:"中国",info6:"亚洲",info7:"China"},
{name:"黄山",info1:"HuangShan",info2:"HuangShan",info3:"HS",info4:"TXN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"黄岩",info1:"HuangYan",info2:"HuangYan",info3:"HY",info4:"HYN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"惠阳",info1:"HuiYang",info2:"HuiYang",info3:"HY",info4:"AHE",info5:"中国",info6:"亚洲",info7:"China"},
{name:"惠灵顿",info1:"Wellington",info2:"Huilingdun",info3:"HLD",info4:"WLG",info5:"新西兰",info6:"大洋洲",info7:"New Zealand"},
{name:"火奴鲁鲁",info1:"Honolulu",info2:"HuoNuLuLu",info3:"hnll",info4:"HNL",info5:"美国",info6:"北美",info7:"USA"},
{name:"胡占德",info1:"Khujand",info2:"Huzhande",info3:"HZD",info4:"LBD",info5:"塔吉克斯坦",info6:"亚洲",info7:"Tajikistan"},
{name:"胡志明市",info1:"HoChiMinh",info2:"HuZhiMingShi",info3:"hzms",info4:"SGN",info5:"越南",info6:"亚洲",info7:"Vietnam"},
{name:"吉安",info1:"JiAn",info2:"JiAn",info3:"JA",info4:"KNC",info5:"中国",info6:"亚洲",info7:"China"},
{name:"济南",info1:"JiNan",info2:"JiNan",info3:"JN",info4:"TNA",info5:"中国",info6:"亚洲",info7:"China"},
{name:"济宁",info1:"JiNing",info2:"JiNing",info3:"JN",info4:"JNG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"吉达",info1:"Jeddah",info2:"JiDa",info3:"jd",info4:"JED",info5:"沙特阿拉伯",info6:"亚洲",info7:"Saudi Arabia"},
{name:"吉林",info1:"JiLin",info2:"JiLin",info3:"JL",info4:"JIL",info5:"中国",info6:"亚洲",info7:"China"},
{name:"吉布提",info1:"Djibouti",info2:"jibuti",info3:"JBT",info4:"JIB",info5:"吉布提",info6:"国际",info7:"Djibouti"},
{name:"吉隆坡",info1:"KualaLumpur",info2:"JiLongPo",info3:"jlp",info4:"KUL",info5:"马来群岛",info6:"亚洲",info7:"Malaysia"},
{name:"贾巴尔普尔",info1:"Jabalpur",info2:"jiabaerpuer",info3:"JBEPE",info4:"JLR",info5:"印度",info6:"亚洲",info7:"India"},
{name:"加德满都",info1:"Kathmandu",info2:"JiaDeManDu",info3:"JDMD",info4:"KTM",info5:"尼泊尔",info6:"亚洲",info7:"Russia"},
{name:"加尔各答",info1:"Calcutta",info2:"jiaergeda",info3:"JEGD",info4:"CCU",info5:"印度",info6:"亚洲",info7:"India"},
{name:"基加利",info1:"Kigali",info2:"jijiali",info3:"JJL",info4:"KGL",info5:"卢旺达",info6:"国际",info7:"Rwanda"},
{name:"基督城",info1:"Christchurch",info2:"Jiducheng",info3:"JDC",info4:"CHC",info5:"新西兰",info6:"大洋洲",info7:"New Zealand"},
{name:"基辅",info1:"Kiev",info2:"Jifu",info3:"jf",info4:"KBP",info5:"乌克兰",info6:"欧洲",info7:"Ukraine"},
{name:"基隆拿",info1:"Kelowna",info2:"JiLongNa",info3:"JLN",info4:"YLW",info5:"加拿大",info6:"北美",info7:"Canada"},
{name:"佳木斯",info1:"JiaMuSi",info2:"JiaMuSi",info3:"JMS",info4:"JMU",info5:"中国",info6:"亚洲",info7:"China"},
{name:"嘉峪关",info1:"JiaYuGuan",info2:"JiaYuGuan",info3:"JYG",info4:"JGN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"江门",info1:"Jiangmen",info2:"Jiangmen",info3:"JM",info4:"JBD",info5:"中国",info6:"亚洲",info7:"China"},
{name:"捷克逊维尔",info1:"Jacksonville",info2:"JieKeXunWeiEr",info3:"jkxwe",info4:"JAX",info5:"美国",info6:"北美",info7:"USA"},
{name:"揭阳",info1:"JieYang",info2:"JieYang",info3:"JY",info4:"SWA",info5:"中国",info6:"亚洲",info7:"China"},
{name:"九寨沟",info1:"JiuZhaiGou",info2:"JiuZhaiGou",info3:"JZG",info4:"JZH",info5:"中国",info6:"亚洲",info7:"China"},
{name:"旧金山",info1:"San Francisco",info2:"Jiujingshan",info3:"JJS",info4:"SFO",info5:"美国",info6:"北美",info7:"United States"},
{name:"晋江",info1:"JinJiang",info2:"JinJiang",info3:"JJ",info4:"JJN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"金边",info1:"PhnomPenh",info2:"JinBian",info3:"jb",info4:"PNH",info5:"柬埔寨",info6:"亚洲",info7:"Kampuchea"},
{name:"金门",info1:"Kinmen",info2:"jinmen",info3:"JM",info4:"KNH",info5:"台湾",info6:"亚洲",info7:"Taiwan"},
{name:"金奈",info1:"Madras",info2:"jinnai",info3:"JN",info4:"MAA",info5:"印度",info6:"亚洲",info7:"India"},
{name:"金沙萨",info1:"Kinshasa",info2:"jinshasa",info3:"JSS",info4:"FIH",info5:"刚果民主共和国",info6:"国际",info7:"Democratic Republic of the Congo"},
{name:"锦州",info1:"JinZhou",info2:"JinZhou",info3:"JZ",info4:"JNZ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"景德镇",info1:"JingDeZhen",info2:"JingDeZhen",info3:"JDZ",info4:"JDZ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"井冈山",info1:"Jinggangshan",info2:'jinggangshan',info3:"JGS",info4:"JGS",info5:"中国",info6:"亚洲",info7:"China"},
{name:"济州",info1:"Cheju",info2:"JiZhou",info3:"jz",info4:"CJU",info5:"韩国",info6:"亚洲",info7:"SouthKorea"},
{name:"荆州、沙市",info1:"JingZhou、ShaShi",info2:"JingZhou、ShaShi",info3:"JZ、SS",info4:"SHS",info5:"中国",info6:"亚洲",info7:"China"},
{name:"九江",info1:"JiuJiang",info2:"JiuJiang",info3:"JJ",info4:"JIU",info5:"中国",info6:"亚洲",info7:"China"},
{name:"卡诺",info1:"Kano",info2:"kanuo",info3:"KN",info4:"KAN",info5:"尼日利亚",info6:"国际",info7:"Nigeria"},
{name:"卡萨布兰卡",info1:"Casablanca",info2:"kasabulanka",info3:"KSBLK",info4:"CAS",info5:"摩洛哥",info6:"国际",info7:"Morocco"},
{name:"卡尔加里",info1:"Calgary",info2:"KaErJiaLi",info3:"KEJL",info4:"YYC",info5:"加拿大",info6:"北美",info7:"Canada"},
{name:"喀布尔",info1:"Kabul",info2:"kabuer",info3:"KBE",info4:"KBL",info5:"阿富汗",info6:"亚洲",info7:"Afghanistan"},
{name:"喀什",info1:"KaShi",info2:"KaShi",info3:"KS",info4:"KHG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"喀土穆",info1:"Khartoum",info2:"katumu",info3:"KTM",info4:"KRT",info5:"苏丹",info6:"国际",info7:"Sudan"},
{name:"喀纳斯",info1:"KaNaSi",info2:"KaNaSi",info3:"KNS",info4:"KJI",info5:"中国",info6:"亚洲",info7:"China"},
{name:"堪培拉",info1:"Canberra",info2:"kanpeila",info3:"kpl",info4:"CBR",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"凯恩斯",info1:"Cairns",info2:"Kaiensi",info3:"kns",info4:"CNS",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"开罗",info1:"Cairo",info2:"kailuo",info3:"KL",info4:"CAI",info5:"埃及",info6:"国际",info7:"Egypt"},
{name:"开普敦",info1:"Cape Town",info2:"kaipudun",info3:"KPD",info4:"CPT",info5:"南非",info6:"国际",info7:"South Africa"},
{name:"科隆",info1:"Cologne-Bonn",info2:"kelong",info3:"KL",info4:"CGN",info5:"德国",info6:"欧洲",info7:"Germany"},
{name:"科伦坡",info1:"Colombo",info2:"kelunpo",info3:"KLP",info4:"CMB",info5:"斯里兰卡",info6:"亚洲",info7:"Sri Lanka"},
{name:"科威特",info1:"Kuwait",info2:"keweite",info3:"KWT",info4:"KWI",info5:"科威特",info6:"亚洲",info7:"Kuwait"},
{name:"科托努",info1:"Cotonou",info2:"ketuonu",info3:"KTN",info4:"COO",info5:"贝宁",info6:"国际",info7:"Benin"},
{name:"克拉克",info1:"Clark",info2:"KeLaKe",info3:"klk",info4:"CRK",info5:"印尼",info6:"亚洲",info7:"Indonesia"},
{name:"克拉科夫",info1:"Krakow",info2:"kelakefu",info3:"KLKF",info4:"KRK",info5:"波兰",info6:"欧洲",info7:"Poland"},
{name:"克拉玛依",info1:"Karamay",info2:"Karamay",info3:"KLMY",info4:"KRY",info5:"中国",info6:"亚洲",info7:"China"},
{name:"克利夫兰",info1:"Cleveland",info2:"KeLiFuLan",info3:"klfl",info4:"CLE",info5:"美国",info6:"北美",info7:"USA"},
{name:"库尔勒",info1:"KuErLe",info2:"KuErLe",info3:"KEL",info4:"KRL",info5:"中国",info6:"亚洲",info7:"China"},
{name:"库车",info1:"KuChe",info2:"KuChe",info3:"KC",info4:"KCA",info5:"中国",info6:"亚洲",info7:"China"},
{name:"昆明",info1:"KunMing",info2:"KunMing",info3:"KM",info4:"KMG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"拉萨",info1:"LaSa",info2:"LaSa",info3:"LS",info4:"LXA",info5:"中国",info6:"亚洲",info7:"China"},
{name:"赖布尔",info1:"Raipur",info2:"laibuer",info3:"LBE",info4:"RPR",info5:"印度",info6:"亚洲",info7:"India"},
{name:"拉各斯",info1:"Lagos",info2:"LaGeSi",info3:"lgs",info4:"LOS",info5:"尼日利亚",info6:"国际",info7:"Nigeria"},
{name:"拉罗汤加",info1:"Rarotonga, Cook Is.",info2:"Laluotangjia",info3:"LSTJ",info4:"RAR",info5:"库克群岛",info6:"大洋洲",info7:"Cook Islands"},
{name:"拉纳卡",info1:"Larnaca",info2:"lanaka",info3:"LNK",info4:"LCA",info5:"塞浦路斯",info6:"欧洲",info7:"Cyprus"},
{name:"拉斯韦加斯",info1:"Las Vegas",info2:"Lasiweijiasi",info3:"LSWJS",info4:"LAS",info5:"美国",info6:"北美",info7:"United States"},
{name:"兰契",info1:"Ranchi",info2:"lanqi",info3:"LQ",info4:"IXR",info5:"印度",info6:"亚洲",info7:"India"},
{name:"兰州",info1:"LanZhou",info2:"LanZhou",info3:"LZ",info4:"LHW",info5:"中国",info6:"亚洲",info7:"China"},
{name:"兰卡威",info1:"Langkawi",info2:'lankawei',info3:"LKW",info4:"LGK",info5:"马来西亚",info6:"亚洲",info7:"Malaysia"},
{name:"丽江",info1:"LiJiang",info2:"LiJiang",info3:"LJ",info4:"LJG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"荔波",info1:"LiBo",info2:"LiBo",info3:"LB",info4:"LLB",info5:"中国",info6:"亚洲",info7:"China"},
{name:"黎平",info1:"LiPing",info2:"LiPing",info3:"LP",info4:"HZH",info5:"中国",info6:"亚洲",info7:"China"},
{name:"里昂",info1:"Lyon",info2:"liang",info3:"LA",info4:"LYS",info5:"法国",info6:"欧洲",info7:"France"},
{name:"里加",info1:"Riga",info2:"lijia",info3:"LI",info4:"RIX",info5:"拉脱维亚",info6:"欧洲",info7:"Latvia"},
{name:"里贾纳",info1:"Regina",info2:"LiJiaNa",info3:"LJN",info4:"YQR",info5:"加拿大",info6:"北美",info7:"Canada"},
{name:"里斯本",info1:"Lisbon",info2:"LiSiBen",info3:"lsb",info4:"LIS",info5:"葡萄牙",info6:"欧洲",info7:"Portugal"},
{name:"里雅恩姆卡拉",info1:"Riyan, Yemen",info2:"liyaenmukala",info3:"LYEMKL",info4:"RIY",info5:"也门",info6:"亚洲",info7:"Yemen"},
{name:"利伯维尔",info1:"Libreville",info2:"liboweier",info3:"LBWE",info4:"LBV",info5:"加蓬",info6:"国际",info7:"Gabon"},
{name:"利马",info1:"Lima",info2:"LiMa",info3:"lm",info4:"LIM",info5:"秘鲁",info6:"北美",info7:"Peru"},
{name:"利雅得",info1:"Riyadh",info2:"liyade",info3:"LYD",info4:"RUH",info5:"沙竺阿拉伯",info6:"亚洲",info7:"Saudi Arabia"},
{name:"连云港",info1:"LianYunGang",info2:"LianYunGang",info3:"LYG",info4:"LYG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"梁平",info1:"LiangPing",info2:"LiangPing",info3:"LP",info4:"LIA",info5:"中国",info6:"亚洲",info7:"China"},
{name:"列城",info1:"Leh",info2:"liecheng",info3:"LC",info4:"IXL",info5:"印度",info6:"亚洲",info7:"India"},
{name:"列宁格勒",info1:"St. Petersburg",info2:"lieninggele",info3:"LNGL",info4:"LED",info5:"俄罗斯",info6:"欧洲",info7:"Russian Federation"},
{name:"罗安达",info1:"Luanda",info2:"luoanda",info3:"LAD",info4:"LAD",info5:"安哥拉",info6:"国际",info7:"Angola"},
{name:"罗德岱堡",info1:"Lauderdale",info2:"LuoDeDaiBao",info3:"lddb",info4:"FLL",info5:"美国",info6:"北美",info7:"USA"},
{name:"罗利",info1:"Raleigh/Durham",info2:"Luoli",info3:"LL",info4:"RDU",info5:"美国",info6:"北美",info7:"United States"},
{name:"罗克汉普顿",info1:"Rockhampton",info2:"Luokehandunpu",info3:"LKHPD",info4:"ROK",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"罗马",info1:"Rome",info2:"LuoMa",info3:"lm",info4:"ROM",info5:"意大利",info6:"欧洲",info7:"Italy"},
{name:"洛杉矶",info1:"LosAngeles",info2:"LuoShanJi",info3:"lsj",info4:"LAX",info5:"美国",info6:"北美",info7:"USA"},
{name:"卢布尔亚那",info1:"Ljubljana",info2:"lubueryana",info3:"LBEYN",info4:"LJU",info5:"斯洛文尼亚",info6:"欧洲",info7:"Slovenia"},
{name:"卢萨卡",info1:"Lusaka",info2:"lusaka",info3:"LSK",info4:"LUN",info5:"赞比亚",info6:"国际",info7:"Zambia"},
{name:"卢森堡",info1:"Luxembourg",info2:"lusenbao",info3:"LSB",info4:"LUX",info5:"卢森堡",info6:"欧洲",info7:"Luxembourg"},
{name:"伦敦",info1:"London",info2:"LunDun",info3:"ld",info4:"LHR",info5:"英国",info6:"欧洲",info7:"England"},
{name:"临沂",info1:"LinYi",info2:"LinYi",info3:"LY",info4:"LYI",info5:"中国",info6:"亚洲",info7:"China"},
{name:"临沧",info1:"LinCang",info2:"LinCang",info3:"LC",info4:"LNJ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"柳州",info1:"LiuZhou",info2:"LiuZhou",info3:"LZ",info4:"LZH",info5:"中国",info6:"亚洲",info7:"China"},
{name:"鹿儿岛",info1:"Kagoshima",info2:"LuErDao",info3:"led",info4:"KOJ",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"泸州",info1:"LuZhou",info2:"LuZhou",info3:"LZ",info4:"LZO",info5:"中国",info6:"亚洲",info7:"China"},
{name:"洛阳",info1:"LuoYang",info2:"LuoYang",info3:"LY",info4:"LYA",info5:"中国",info6:"亚洲",info7:"China"},
{name:"曼谷",info1:"Bangkok",info2:"ManGu",info3:"mg",info4:"BKK",info5:"泰国",info6:"亚洲",info7:"Thailand"},
{name:"马德里",info1:"Madrid",info2:"MaDeLi",info3:"mdl",info4:"MAD",info5:"西班牙",info6:"欧洲",info7:"Spain"},
{name:"马拉加",info1:"Malaga",info2:"malajia",info3:"MLJ",info4:"AGP",info5:"西班牙",info6:"欧洲",info7:"Spain"},
{name:"马斯喀特",info1:"Muscat",info2:"masikate",info3:"MSKT",info4:"MCT",info5:"阿曼",info6:"亚洲",info7:"Oman"},
{name:"马尼拉",info1:"Manila",info2:"MaNiLa",info3:"mnl",info4:"MNL",info5:"菲律宾",info6:"亚洲",info7:"Philippines"},
{name:"马累",info1:"Male",info2:"Male",info3:"ML",info4:"MLE",info5:"马尔代夫",info6:"亚洲",info7:"Maldives"},
{name:"马赛",info1:"Marseille",info2:"masai",info3:"MS",info4:"MRS",info5:"法国",info6:"欧洲",info7:"France"},
{name:"迈阿密",info1:"Miami",info2:"Maiami",info3:"MAM",info4:"MIA",info5:"美国",info6:"北美",info7:"United States"},
{name:"麦凯",info1:"Mackay",info2:"Maikai",info3:"MK",info4:"MKY",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"麦克默里堡",info1:"Fort Mcmurray",info2:"MaiKeMoLiBao",info3:"MKMLB",info4:"YMM",info5:"加拿大",info6:"北美",info7:"Canada"},
{name:"曼彻斯特",info1:"Manchester",info2:"ManCheSiTe",info3:"mcst",info4:"MAN",info5:"英国",info6:"欧洲",info7:"UK"},
{name:"满洲里",info1:"ManZhouLi",info2:"ManZhouLi",info3:"MZL",info4:"NZH",info5:"中国",info6:"亚洲",info7:"China"},
{name:"芒特艾萨",info1:"Mount Isa",info2:"Mangteaisa",info3:"MTAS",info4:"ISA",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"梅县",info1:"MeiXian",info2:"MeiXian",info3:"MX",info4:"MXZ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"墨尔本",info1:"Melbourne",info2:"MoErBen",info3:"meb",info4:"MEL",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"莫尔斯比港",info1:"Port Moresby",info2:"Moersibigang",info3:"MESBG",info4:"POM",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"漠河",info1:"MoHe",info2:"MoHe",info3:"MH",info4:"OHE",info5:"中国",info6:"亚洲",info7:"China"},
{name:"莫斯科",info1:"Moscow",info2:"MoSiKe",info3:"msk",info4:"MOW",info5:"俄罗斯",info6:"欧洲",info7:"Russia"},
{name:"米尔迪拉",info1:"Mildura",info2:"Mierdila",info3:"MEDL",info4:"MQL",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"密尔沃基",info1:"Milwaukee",info2:"Mierwoji",info3:"MEWJ",info4:"MKE",info5:"美国",info6:"北美",info7:"United States"},
{name:"米兰",info1:"Milan",info2:"MiLan",info3:"ml",info4:"MIL",info5:"意大利",info6:"欧洲",info7:"Italy"},
{name:"绵阳",info1:"MianYang",info2:"MianYang",info3:"MY",info4:"MIG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"棉兰",info1:"Medan",info2:"mianlan",info3:"ML",info4:"MES",info5:"印度尼西亚",info6:"亚洲",info7:"Indonesia"},
{name:"名古屋",info1:"Nagoya",info2:"MingGuWu",info3:"mgw",info4:"NGO",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"明斯克",info1:"Minsk",info2:"mingsike",info3:"MSK",info4:"MSQ",info5:"白俄罗斯",info6:"欧洲",info7:"Belarus"},
{name:"明尼阿波利斯",info1:"Minneapolis",info2:"Mingniabolisi",info3:"MNABLS",info4:"MSP",info5:"美国",info6:"北美",info7:"United States"},
{name:"蒙特利尔",info1:"Montreal",info2:"Mengtelier",info3:"MTLE",info4:"YMQ",info5:"加拿大",info6:"北美",info7:"Canada"},
{name:"孟菲斯",info1:"Memphis",info2:"MengFeiSi",info3:"mfs",info4:"MEM",info5:"美国",info6:"北美",info7:"USA"},
{name:"孟买",info1:"Mumbai/Bombay",info2:"mengmai",info3:"MM",info4:"BOM",info5:"印度",info6:"亚洲",info7:"India"},
{name:"牡丹江",info1:"MuDanJiang",info2:"MuDanJiang",info3:"MDJ",info4:"MDG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"慕尼黑",info1:"Munich",info2:"MuNiHei",info3:"mnh",info4:"MUC",info5:"德国",info6:"欧洲",info7:"Germany"},
{name:"纳迪",info1:"Nadi",info2:"Nadi",info3:"ND",info4:"NAN",info5:"斐济",info6:"大洋洲",info7:"Fiji"},
{name:"那拉提",info1:"NaLaTi",info2:"NaLaTi",info3:"NLT",info4:"NLT",info5:"中国",info6:"亚洲",info7:"China"},
{name:"那格浦尔",info1:"Nagpur",info2:"nagepuer",info3:"NGPE",info4:"NAG",info5:"印度",info6:"亚洲",info7:"India"},
{name:"南昌",info1:"NanChang",info2:"NanChang",info3:"NC",info4:"KHN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"南充",info1:"NanChong",info2:"NanChong",info3:"NC",info4:"NAO",info5:"中国",info6:"亚洲",info7:"China"},
{name:"南海",info1:"Nanhai",info2:"Nanhai",info3:"NH",info4:"NFF",info5:"中国",info6:"亚洲",info7:"China"},
{name:"南京",info1:"NanJing",info2:"NanJing",info3:"NJ",info4:"NKG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"南宁",info1:"NanNing",info2:"NanNing",info3:"NN",info4:"NNG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"南通",info1:"NanTong",info2:"NanTong",info3:"NT",info4:"NTG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"南阳",info1:"NanYang",info2:"NanYang",info3:"NY",info4:"NNY",info5:"中国",info6:"亚洲",info7:"China"},
{name:"宁波",info1:"NingBo",info2:"NingBo",info3:"NB",info4:"NGB",info5:"中国",info6:"亚洲",info7:"China"},
{name:"尼斯",info1:"Nice",info2:"nisi",info3:"NS",info4:"NCE",info5:"法国",info6:"欧洲",info7:"France"},
{name:"纽约",info1:"NewYork",info2:"NiuYue",info3:"ny",info4:"NYC",info5:"美国",info6:"北美",info7:"USA"},
{name:"纽瓦克",info1:"Newark",info2:"NiuWaKe",info3:"nwk",info4:"EWR",info5:"美国",info6:"北美",info7:"USA"},
{name:"纽卡斯尔",info1:"Newcastle",info2:"Niukasier",info3:"NKSE",info4:"NTL",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"纽卡斯尔",info1:"Newcastle",info2:"Niukasier",info3:"NKSE",info4:"NCL",info5:"英国",info6:"欧洲",info7:"UK"},
{name:"内罗毕",info1:"Nairobi",info2:"neiluobi",info3:"NLB",info4:"NBO",info5:"肯尼亚",info6:"国际",info7:"Kenya"},
{name:"攀枝花",info1:"PanZhiHua",info2:"PanZhiHua",info3:"PZH",info4:"PZI",info5:"中国",info6:"亚洲",info7:"China"},
{name:"浦那",info1:"Poona",info2:"puna",info3:"PN",info4:"PNQ",info5:"印度",info6:"亚洲",info7:"India"},
{name:"浦项",info1:"Pohang",info2:"puxiang",info3:"PX",info4:"KPO",info5:"韩国",info6:"亚洲",info7:"South Korea"},
{name:"珀斯",info1:"Perth",info2:"posi",info3:"PS",info4:"PER",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"普吉",info1:"Phuket",info2:"PuJi",info3:"pj",info4:"HKT",info5:"泰国",info6:"亚洲",info7:"Thailand"},
{name:"普罗瑟派恩",info1:"Proserpine",info2:"Puluosepaien",info3:"PLSPE",info4:"PPP",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"齐齐哈尔",info1:"QiQiHaEr",info2:"QiQiHaEr",info3:"QQHE",info4:"NDG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"且末",info1:"QieMo",info2:"QieMo",info3:"QM",info4:"IQM",info5:"中国",info6:"亚洲",info7:"China"},
{name:"乔治王子城",info1:"prince George",info2:"QiaoZhiWangZiCheng",info3:"QZWZC",info4:"YXS",info5:"加拿大",info6:"北美",info7:"Canada"},
{name:"青岛",info1:"QingDao",info2:"QingDao",info3:"QD",info4:"TAO",info5:"中国",info6:"亚洲",info7:"China"},
{name:"清迈",info1:"Chiang Mai",info2:'qingmai',info3:"QM",info4:"CNX",info5:"泰国",info6:"亚洲",info7:"Thailand"},
{name:"清州",info1:"Chongju",info2:"QingZhou",info3:"qz",info4:"CJJ",info5:"韩国",info6:"亚洲",info7:"SouthKorea"},
{name:"庆阳",info1:"QingYang",info2:"QingYang",info3:"QY",info4:"IQN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"秦皇岛",info1:"QinHuangDao",info2:"QinHuangDao",info3:"QHD",info4:"SHP",info5:"中国",info6:"亚洲",info7:"China"},
{name:"衢州",info1:"QuZhou",info2:"QuZhou",info3:"QZ",info4:"JUZ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"泉州",info1:"QuanZhou",info2:"QuanZhou",info3:"QZ",info4:"JJN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"黔江机场",info1:"Qianjiang",info2:"QianJiang",info3:"QJ",info4:"JIQ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"日内瓦",info1:"Geneva",info2:"RiNeiWa",info3:"rnw",info4:"GVA",info5:"瑞士",info6:"欧洲",info7:"Switzerland"},
{name:"塞班",info1:"Saipan",info2:"SaiBan",info3:"sb",info4:"SPN",info5:"美国",info6:"北美",info7:"USA"},
{name:"萨格勒布",info1:"Zagreb",info2:"sagelebu",info3:"SGLB",info4:"ZAG",info5:"克罗地亚",info6:"欧洲",info7:"Croatia"},
{name:"萨斯卡通",info1:"Sackatoon",info2:"SaSiKaTong",info3:"SSKT",info4:"YXE",info5:"加拿大",info6:"北美",info7:"Canada"},
{name:"萨那",info1:"Sana'a",info2:"sana",info3:"SN",info4:"SAH",info5:"也门",info6:"亚洲",info7:"Yemen"},
{name:"沙迦",info1:"Sharjah",info2:"ShaJia",info3:"sj",info4:"SHJ",info5:"阿拉伯联合酋长国",info6:"亚洲",info7:"UnitedArabEmirates"},
{name:"汕头",info1:"Shantou",info2:"shantou",info3:"ST",info4:"SWA",info5:"中国",info6:"亚洲",info7:"China"},
{name:"上海虹桥",info1:"ShangHaiHongQiao",info2:"ShangHaiHongQiao",info3:"SHHQ",info4:"SHA",info5:"中国",info6:"亚洲",info7:"China"},
{name:"上海浦东",info1:"ShangHaiPuDong",info2:"ShangHaiPuDong",info3:"SHPD",info4:"PVG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"三亚",info1:"SanYa",info2:"SanYa",info3:"SY",info4:"SYX",info5:"中国",info6:"亚洲",info7:"China"},
{name:"沈阳",info1:"ShenYang",info2:"ShenYang",info3:"SY",info4:"SHE",info5:"中国",info6:"亚洲",info7:"China"},
{name:"深圳",info1:"ShenZhen",info2:"ShenZhen",info3:"SZ",info4:"SZX",info5:"中国",info6:"亚洲",info7:"China"},
{name:"圣地亚哥",info1:"San Diego",info2:"Shengdiyage",info3:"SDYG",info4:"SAN",info5:"美国",info6:"北美",info7:"United States"},
{name:"圣何塞",info1:"San Jose",info2:"Shenghesai",info3:"SHS",info4:"SJC",info5:"美国",info6:"北美",info7:"United States"},
{name:"苏梅岛",info1:"Koh Samui",info2:'shumeidao',info3:"SMD",info4:"USM",info5:"泰国",info6:"亚洲",info7:"Thailand"},
{name:"泗水",info1:"Surabaya",info2:"Surabaya",info3:"SS",info4:"SUB",info5:"中国",info6:"亚洲",info7:"China"},
{name:"沙巴",info1:"Sabah",info2:'shaba',info3:"SB",info4:"BKI",info5:"马来西亚",info6:"亚洲",info7:"Malaysia"},
{name:"韶关",info1:"ShaoGuan",info2:"ShaoGuan",info3:"SG",info4:"SHG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"鄯善",info1:"ShanShan",info2:"ShanShan",info3:"SS",info4:"SXJ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"思茅",info1:"SiMao",info2:"SiMao",info3:"SM",info4:"SYM",info5:"中国",info6:"亚洲",info7:"China"},
{name:"斯图加特",info1:"Stuttgart",info2:"Situjiate",info3:"STJT",info4:"STR",info5:"德国",info6:"欧洲",info7:"Germany"},
{name:"斯德哥尔摩",info1:"Stockholm",info2:"SiDeGeErMo",info3:"sdgem",info4:"STO",info5:"瑞典",info6:"欧洲",info7:"Sweden"},
{name:"斯图加特",info1:"Stuttgart",info2:"Situjiate",info3:"STJT",info4:"STR",info5:"德国",info6:"欧洲",info7:"Germany"},
{name:"斯特拉斯堡",info1:"Strasbourg",info2:"sitelasibao",info3:"STLSB",info4:"SXB",info5:"法国",info6:"欧洲",info7:"France"},
{name:"索非亚",info1:"Sofia",info2:"suofeiya",info3:"SFY",info4:"SOF",info5:"保加利亚",info6:"欧洲",info7:"Bulgaria"},
{name:"苏黎世",info1:"Zurich",info2:"SuLiShi",info3:"sls",info4:"ZRH",info5:"瑞典",info6:"欧洲",info7:"Switzerland"},
{name:"石家庄",info1:"ShiJiaZhuang",info2:"ShiJiaZhuang",info3:"SJZ",info4:"SJW",info5:"中国",info6:"亚洲",info7:"China"},
{name:"松山",info1:"Matsuyama",info2:"songshan",info3:"SS",info4:"MYJ",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"首尔",info1:"Seoul",info2:"ShouEr",info3:"se",info4:"SEL",info5:"韩国",info6:"亚洲",info7:"SouthKorea"},
{name:"顺德",info1:"Shunde",info2:"Shunde",info3:"SD",info4:"NDH",info5:"中国",info6:"亚洲",info7:"China"},
{name:"塔城",info1:"TaCheng",info2:"TaCheng",info3:"TC",info4:"TCG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"塔什干",info1:"Tashkent",info2:"TaShenGan",info3:"tsg",info4:"TAS",info5:"乌兹别克斯坦",info6:"亚洲",info7:"Uzbekistan"},
{name:"塔林",info1:"Tallinn",info2:"talin",info3:"TL",info4:"TLL",info5:"爱沙尼亚",info6:"欧洲",info7:"Estonia"},
{name:"塔那那利佛",info1:"Antananarivo",info2:"tananalifo",info3:"TNNLF",info4:"TNR",info5:"马达加斯加",info6:"国际",info7:"Madagascar"},
{name:"台北",info1:"TaiPei",info2:"TaiBei",info3:"TB",info4:"TPE",info5:"中国",info6:"亚洲",info7:"Taiwan"},
{name:"台山",info1:"Taishan",info2:"Taishan",info3:"TS",info4:"THJ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"太原",info1:"TaiYuan",info2:"TaiYuan",info3:"TY",info4:"TYN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"台中",info1:"Taichung",info2:"Taizhong",info3:"TZ",info4:"RMQ",info5:"台湾",info6:"亚洲",info7:"Taiwan"},
{name:"坦帕",info1:"Tampa",info2:"TanPa",info3:"tp",info4:"TPA",info5:"美国",info6:"北美",info7:"USA"},
{name:"汤斯维尔",info1:"Townsville",info2:"Tangsiweier",info3:"TSWE",info4:"TSV",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"腾冲",info1:"TengChong",info2:"TengChong",info3:"TC",info4:"TCZ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"天津",info1:"TianJin",info2:"TianJin",info3:"TJ",info4:"TSN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"铜仁",info1:"TongRen",info2:"TongRen",info3:"TR",info4:"TEN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"吐鲁番",info1:"TuLuFan",info2:"TuLuFan",info3:"TLB",info4:"TLQ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"突尼斯城",info1:"Tunis",info2:"tunisicheng",info3:"TNSC",info4:"TUN",info5:"突尼斯",info6:"国际",info7:"Tunisia"},
{name:"万州",info1:"WanZhou",info2:"WanZhou",info3:"WZ",info4:"WXN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"万象",info1:"Vientiane",info2:"wanxiang",info3:"WX",info4:"VTE",info5:"老挝",info6:"亚洲",info7:"Laos"},
{name:"万鸦老",info1:"Manado",info2:"wanyalao",info3:"WYL",info4:"MDC",info5:"印度尼西亚",info6:"亚洲",info7:"Indonesia"},
{name:"潍坊",info1:"WeiFang",info2:"WeiFang",info3:"WF",info4:"WEF",info5:"中国",info6:"亚洲",info7:"China"},
{name:"威海",info1:"WeiHai",info2:"WeiHai",info3:"WH",info4:"WEH",info5:"中国",info6:"亚洲",info7:"China"},
{name:"威尼斯",info1:"Venice",info2:"weinisi",info3:"WNS",info4:"VCE",info5:"意大利",info6:"欧洲",info7:"Italy"},
{name:"维也纳",info1:"Vienna",info2:"WeiYeNa",info3:"wyn",info4:"VIE",info5:"奥地利",info6:"欧洲",info7:"Austria"},
{name:"温哥华",info1:"Vancouver",info2:"WenGeHua",info3:"wgh",info4:"YVR",info5:"加拿大",info6:"北美",info7:"Canada"},
{name:"文山",info1:"WenShan",info2:"WenShan",info3:"WS",info4:"WNH",info5:"中国",info6:"亚洲",info7:"China"},
{name:"温州",info1:"WenZhou",info2:"WenZhou",info3:"WZ",info4:"WNZ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"温尼伯",info1:"Winnipeg",info2:"WenNiBo",info3:"WNB",info4:"YWG",info5:"加拿大",info6:"北美",info7:"Canada"},
{name:"吴哥窟",info1:"Angkor",info2:"WuGeKu",info3:"wgk",info4:"REP",info5:"柬埔寨",info6:"亚洲",info7:"Kampuchea"},
{name:"梧州",info1:"WuZhou",info2:"WuZhou",info3:"WZ",info4:"WUZ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"武汉",info1:"WuHan",info2:"WuHan",info3:"WH",info4:"WUH",info5:"中国",info6:"亚洲",info7:"China"},
{name:"乌鲁木齐",info1:"Urumqi",info2:"WuLuMuQi",info3:"WLMQ",info4:"URC",info5:"中国",info6:"亚洲",info7:"China"},
{name:"无锡",info1:"WuXi",info2:"WuXi",info3:"WX",info4:"WUX",info5:"中国",info6:"亚洲",info7:"China"},
{name:"武夷山",info1:"WuYiShan",info2:"WuYiShan",info3:"WYS",info4:"WUS",info5:"中国",info6:"亚洲",info7:"China"},
{name:"渥太华",info1:"Ottawa",info2:"Wotaihua",info3:"WTH",info4:"YOW",info5:"加拿大",info6:"北美",info7:"Canada"},
{name:"西昌",info1:"XiChang",info2:"XiChang",info3:"XC",info4:"XIC",info5:"中国",info6:"亚洲",info7:"China"},
{name:"西安",info1:"XiAn",info2:"XiAn",info3:"XA",info4:"SIA",info5:"中国",info6:"亚洲",info7:"China"},
{name:"西宁",info1:"XiNing",info2:"XiNing",info3:"XN",info4:"XNN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"西双版纳",info1:"XiShuangBanNa",info2:"XiShuangBanNa",info3:"XSBN",info4:"JHG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"厦门",info1:"XiaMen",info2:"XiaMen",info3:"XM",info4:"XMN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"悉尼",info1:"Sydney",info2:"XiNi",info3:"xn",info4:"SYD",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"夏洛特",info1:"Charlotte",info2:"Xialuote",info3:"xLT",info4:"CLT",info5:"美国",info6:"北美",info7:"United States"},
{name:"岘港",info1:"Danang",info2:"XianGang",info3:"XG",info4:"DAD",info5:"越南",info6:"亚洲",info7:"Vietnam"},
{name:"仙台",info1:"Sendai",info2:"XianTai",info3:"xt",info4:"SDJ",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"暹粒",info1:"SiemReap",info2:"XianLi",info3:"xl",info4:"REP",info5:"柬埔寨",info6:"亚洲",info7:"Kampuchea"},
{name:"小松",info1:"Komatsu",info2:"xiaosong",info3:"XS",info4:"KMQ",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"香港",info1:"HongKong",info2:"XiangGang",info3:"XG",info4:"HKG",info5:"中国",info6:"亚洲",info7:"ChinaLand"},
{name:"锡林浩特",info1:"XiLinHaoTe",info2:"XiLinHaoTe",info3:"XLHT",info4:"XIL",info5:"中国",info6:"亚洲",info7:"China"},
{name:"西雅图",info1:"Seattle",info2:"Xiyatu",info3:"XYT",info4:"SEA",info5:"美国",info6:"北美",info7:"United States"},
{name:"新奥尔良",info1:"New Orleans",info2:"Xinaoerliang",info3:"XAEL",info4:"MSY",info5:"美国",info6:"北美",info7:"United States"},
{name:"新德里",info1:"New Delhi",info2:"XinDeLi",info3:"XDL",info4:"DEL",info5:"印度",info6:"亚洲",info7:"India"},
{name:"新泻",info1:"Niigata",info2:"XinXie",info3:"xx",info4:"KIJ",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"新加坡",info1:"Singapore",info2:"XinJiaPo",info3:"xjp",info4:"SIN",info5:"新加坡",info6:"亚洲",info7:"Singapore"},
{name:"新西伯利亚",info1:"Novosibirsk",info2:"XinXiBoLiYa",info3:"xxbly",info4:"OVB",info5:"俄罗斯",info6:"欧洲",info7:"Russia"},
{name:"辛辛那提",info1:"Cincinnati",info2:"XinXinNaTi",info3:"xxnt",info4:"CVG",info5:"美国",info6:"北美",info7:"USA"},
{name:"休斯顿",info1:"Houston",info2:"XiuSiDun",info3:"xsd",info4:"IAH",info5:"美国",info6:"北美",info7:"USA"},
{name:"兴义",info1:"XingYi",info2:"XingYi",info3:"XY",info4:"ACX",info5:"中国",info6:"亚洲",info7:"China"},
{name:"徐州",info1:"XuZhou",info2:"XuZhou",info3:"XZ",info4:"XUZ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"襄阳",info1:"XiangYang",info2:"XiangYang",info3:"XY",info4:"XFN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"雅典",info1:"Athena",info2:"YaDian",info3:"yd",info4:"ATH",info5:"希腊",info6:"欧洲",info7:"Greece"},
{name:"雅加达",info1:"Jakarta",info2:"YaJiaDa",info3:"yjd",info4:"JKT",info5:"印尼",info6:"亚洲",info7:"Indonesia"},
{name:"亚特兰大",info1:"Atlanta",info2:"YaTeLanDa",info3:"ytld",info4:"ATL",info5:"美国",info6:"北美",info7:"USA"},
{name:"亚的斯亚贝巴",info1:"Addis Ababa",info2:"yadesiyabeiba",info3:"YDSYBB",info4:"ADD",info5:"埃塞俄比亚",info6:"国际",info7:"Ethiopia"},
{name:"盐城",info1:"YanCheng",info2:"YanCheng",info3:"YC",info4:"YNZ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"盐湖城",info1:"SaltLakeCity",info2:"YanHuCheng",info3:"yhc",info4:"SLC",info5:"美国",info6:"北美",info7:"USA"},
{name:"延安",info1:"YanAn",info2:"YanAn",info3:"YA",info4:"ENY",info5:"中国",info6:"亚洲",info7:"China"},
{name:"延吉",info1:"YanJi",info2:"YanJi",info3:"YJ",info4:"YNJ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"烟台",info1:"YanTai",info2:"YanTai",info3:"YT",info4:"YNT",info5:"中国",info6:"亚洲",info7:"China"},
{name:"仰光",info1:"Rangoon",info2:"YangGuang",info3:"yg",info4:"RGN",info5:"缅甸",info6:"亚洲",info7:"Burma"},
{name:"扬州",info1:"Yangzhou",info2:"Yangzhou",info3:"YZ",info4:"YTY",info5:"中国",info6:"亚洲",info7:"China"},
{name:"宜宾",info1:"YiBin",info2:"YiBin",info3:"YB",info4:"YBP",info5:"中国",info6:"亚洲",info7:"China"},
{name:"宜昌",info1:"YiChang",info2:"YiChang",info3:"YC",info4:"YIH",info5:"中国",info6:"亚洲",info7:"China"},
{name:"依尔库茨克",info1:"Irkutsk",info2:"YiErKuCiKe",info3:"yekck",info4:"IKT",info5:"俄罗斯",info6:"欧洲",info7:"Russia"},
{name:"伊春",info1:"YiChun",info2:"YiChun",info3:"YC",info4:"LDS",info5:"中国",info6:"亚洲",info7:"China"},
{name:"伊宁",info1:"YiNing",info2:"YiNing",info3:"YN",info4:"YIN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"伊斯坦布尔",info1:"Istanbul",info2:"yisitanbuer",info3:"YSTBE",info4:"IST",info5:"土耳其",info6:"欧洲",info7:"Turkey"},
{name:"义乌",info1:"YiWu",info2:"YiWu",info3:"YW",info4:"YIW",info5:"中国",info6:"亚洲",info7:"China"},
{name:"伊斯兰堡",info1:"Islamabad",info2:"yisilanbao",info3:"YSLB",info4:"ISB",info5:"巴基斯坦",info6:"亚洲",info7:"Pakistan"},
{name:"永州",info1:"YongZhou",info2:"YongZhou",info3:"YZ",info4:"LLF",info5:"中国",info6:"亚洲",info7:"China"},
{name:"榆林",info1:"YuLin",info2:"YuLin",info3:"YL",info4:"UYN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"运城",info1:"YunCheng",info2:"YunCheng",info3:"YC",info4:"YCU",info5:"中国",info6:"亚洲",info7:"China"},
{name:"银川",info1:"YinChuan",info2:"YinChuan",info3:"YC",info4:"INC",info5:"中国",info6:"亚洲",info7:"China"},
{name:"印第安纳波利斯",info1:"Indianapolis",info2:"Yindiannabolisi",info3:"YDANBLS",info4:"IND",info5:"美国",info6:"北美",info7:"United States"},
{name:"约翰内斯堡",info1:"Johannesburg",info2:"yuehanneisibao",info3:"YHNSB",info4:"JNB",info5:"南非",info6:"国际",info7:"South Africa"},
{name:"湛江",info1:"ZhanJiang",info2:"ZhanJiang",info3:"ZJ",info4:"ZHA",info5:"中国",info6:"亚洲",info7:"China"},
{name:"斋浦尔",info1:"Jaipur",info2:"zhaipuer",info3:"ZPE",info4:"JAI",info5:"印度",info6:"亚洲",info7:"India"},
{name:"昭通",info1:"ZhaoTong",info2:"ZhaoTong",info3:"ZT",info4:"ZAT",info5:"中国",info6:"亚洲",info7:"China"},
{name:"张家界",info1:"ZhangJiaJie",info2:"ZhangJiaJie",info3:"ZJJ",info4:"DYG",info5:"中国",info6:"亚洲",info7:"China"},
{name:"郑州",info1:"ZhengZhou",info2:"ZhengZhou",info3:"ZZ",info4:"CGO",info5:"中国",info6:"亚洲",info7:"China"},
{name:"舟山",info1:"ZhouShan",info2:"Zhoui",info3:"ZH",info4:"HSN",info5:"中国",info6:"亚洲",info7:"China"},
{name:"珠海",info1:"ZhuHai",info2:"ZhuHai",info3:"ZY",info4:"ZUH",info5:"中国",info6:"亚洲",info7:"China"},
{name:"札幌",info1:"Sapporo",info2:"ZhaHuang",info3:"zh",info4:"SPK",info5:"日本",info6:"亚洲",info7:"Japan"},
{name:"芝加哥",info1:"Chicago",info2:"ZhiJiaGe",info3:"zjg",info4:"ORD",info5:"美国",info6:"北美",info7:"USA"},
{name:"中山",info1:"Zhongshan",info2:"Zhongshan",info3:"ZS",info4:"HHS",info5:"中国",info6:"亚洲",info7:"China"},
{name:"遵义",info1:"ZunYi",info2:"ZunYShan",info3:"ZS",info4:"ZYI",info5:"中国",info6:"亚洲",info7:"China"},
{name:"池州",info1:"ChiZhou",info2:"ChiZhou",info3:"CZ",info4:"JUH",info5:"中国",info6:"亚洲",info7:"China"},
{name:"抚远",info1:"FuYuan",info2:"FuYuan",info3:"FY",info4:"FYJ",info5:"中国",info6:"亚洲",info7:"China"},
{name:"鸡西",info1:"JiXi",info2:"JiXi",info3:"JX",info4:"JXA",info5:"中国",info6:"亚洲",info7:"China"},
{name:"通辽",info1:"TongLiao",info2:"TongLiao",info3:"TL",info4:"TGO",info5:"中国",info6:"亚洲",info7:"China"},
{name:"布里斯班",info1:"Brisbane",info2:"BuLiShiBan",info3:"BLSB",info4:"BNE",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"奥斯丁",info1:"Austin",info2:"AoSiDing",info3:"ASD",info4:"AUS",info5:"美国",info6:"北美",info7:"USA"},
{name:"纳什维尔",info1:"Nashville",info2:"NaShenWeiEr",info3:"NSWE",info4:"BNA",info5:"美国",info6:"北美",info7:"USA"},
{name:"蒙特雷(美)",info1:"Monterey(USA)",info2:"MengTeLei",info3:"MTL",info4:"MRY",info5:"美国",info6:"北美",info7:"USA"},
{name:"卡胡卢伊",info1:"Kahului",info2:"KaHuLuYi",info3:"KHLY",info4:"OGG",info5:"美国",info6:"北美",info7:"USA"},
{name:"菲尼克斯",info1:"Phoenix",info2:"FeiNiKeSi",info3:"FNKS",info4:"PHX",info5:"美国",info6:"北美",info7:"USA"},
{name:"圣芭芭拉",info1:"Santabarbara",info2:"ShengBaBaLa",info3:"SBBL",info4:"SBA",info5:"美国",info6:"北美",info7:"USA"},
{name:"图森",info1:"Tucson",info2:"TuSen",info3:"TS",info4:"TUS",info5:"美国",info6:"北美",info7:"USA"},
{name:"弗雷斯诺",info1:"Fresno",info2:"FuLeiSiNuo",info3:"FLSN",info4:"FAT",info5:"美国",info6:"北美",info7:"USA"},
{name:"安克雷奇",info1:"Anchorage",info2:"AnKeLeiQi",info3:"AKLQ",info4:"ANC",info5:"美国",info6:"北美",info7:"USA"},
{name:"博兹曼",info1:"Bozeman",info2:"BoZiMan",info3:"BZM",info4:"BZN",info5:"美国",info6:"北美",info7:"USA"},
{name:"斯波坎",info1:"Spokane",info2:"SiBoKan",info3:"SBK",info4:"GEG",info5:"美国",info6:"北美",info7:"USA"},
{name:"堪萨斯城",info1:"KanSascity",info2:"KanSaSiCheng",info3:"KSSC",info4:"MCI",info5:"美国",info6:"北美",info7:"USA"},
{name:"萨克拉门托",info1:"Sacramento",info2:"SaKeLaMenTuo",info3:"SKLMT",info4:"SMF",info5:"美国",info6:"北美",info7:"USA"},
{name:"梅德福",info1:"Medford",info2:"MeiDeFu",info3:"MDF",info4:"MFR",info5:"美国",info6:"北美",info7:"USA"},
{name:"圣罗莎",info1:"Santarosa",info2:"ShengLuoSha",info3:"SLS",info4:"STS",info5:"美国",info6:"北美",info7:"USA"},
{name:"瓜达拉哈拉",info1:"Guadalajara",info2:"GuaDaLaHaLa",info3:"GDLHL",info4:"GDL",info5:"墨西哥",info6:"北美",info7:"Mexico"},
{name:"坎昆",info1:"Cancun",info2:"KanKun",info3:"KK",info4:"CUN",info5:"墨西哥",info6:"北美",info7:"Mexico"},
{name:"圣荷西",info1:"Sanjosecabo",info2:"ShengHeXi",info3:"SHX",info4:"SJD",info5:"墨西哥",info6:"北美",info7:"Mexico"},
{name:"曼萨尼略",info1:"Manzanillo",info2:"ManSaNiLue",info3:"MSNL",info4:"ZLO",info5:"墨西哥",info6:"北美",info7:"Mexico"},
{name:"墨西哥城",info1:"Mexicocity",info2:"MoXiGeCheng",info3:"MXGC",info4:"MEX",info5:"墨西哥",info6:"北美",info7:"Mexico"},
{name:"巴亚尔塔港",info1:"Puertoescondido",info2:"BaYaErTaGang",info3:"BYETG",info4:"PVR",info5:"墨西哥",info6:"北美",info7:"Mexico"},
{name:"梅里达",info1:"Merida",info2:"MeiLiDa",info3:"MLD",info4:"MID",info5:"墨西哥",info6:"北美",info7:"Mexico"},
{name:"蒙特雷(墨西哥)",info1:"Monterrey(Mexico)",info2:"MengTeLei",info3:"MTL",info4:"MTY",info5:"墨西哥",info6:"北美",info7:"Mexico"},
{name:"库利阿坎",info1:"Culiacan",info2:"KuLiAKan",info3:"KLAK",info4:"CUL",info5:"墨西哥",info6:"北美",info7:"Mexico"},
{name:"加拉加斯",info1:"Caracas",info2:"JiaLaJiaSi",info3:"JLJS",info4:"CCS",info5:"委内瑞拉",info6:"国际",info7:"Venezuela"},
{name:"圣保罗",info1:"Saopaulo",info2:"ShengBaoLuo",info3:"SBL",info4:"GRU",info5:"巴西",info6:"国际",info7:"Brazil"},
{name:"里约热内卢",info1:"Riodejaneiro",info2:"LiYueReNeiLu",info3:"LYRNL",info4:"GIG",info5:"巴西",info6:"国际",info7:"Brazil"},
{name:"帕拉马里博",info1:"Paramaribo",info2:"PaLaMaLiBo",info3:"PLMLB",info4:"PBM",info5:"苏里南",info6:"国际",info7:"Surinam"},
{name:"巴拿马城",info1:"Panamacity",info2:"BaNaMaCheng",info3:"BNMC",info4:"PTY",info5:"巴拿马",info6:"国际",info7:"Panama"},
{name:"波哥大",info1:"Bogota",info2:"BoGeDa",info3:"BGD",info4:"BOG",info5:"哥伦比亚",info6:"国际",info7:"Colombia"},
{name:"圣地亚哥",info1:"Santiago",info2:"ShengDiYaGe",info3:"SDYG",info4:"SCL",info5:"智利",info6:"国际",info7:"Chile"},
{name:"布宜诺斯艾利斯",info1:"Buenosaires",info2:"BuYiNuoSiAiLiSi",info3:"BYNSALS",info4:"EZE",info5:"阿根廷",info6:"国际",info7:"Argentina"},
{name:"査谟",info1:"Jammu",info2:"ChaMo",info3:"CM",info4:"IXJ",info5:"印度",info6:"亚洲",info7:"India"},
{name:"勒克瑙",info1:"Lucknow",info2:"LeKeNao",info3:"LKN",info4:"LKO",info5:"印度",info6:"亚洲",info7:"India"},
{name:"特里凡得琅",info1:"Thiruvananthapura",info2:"TeLiFanDeLang",info3:"TLFDL",info4:"TRV",info5:"印度",info6:"亚洲",info7:"India"},
{name:"瓦拉纳西",info1:"Varanasi",info2:"WaLaNaXi",info3:"WLNX",info4:"VNS",info5:"印度",info6:"亚洲",info7:"India"},
{name:"卡利刻特",info1:"Kozhikode",info2:"KaLiKeTe",info3:"KLKT",info4:"CCJ",info5:"印度",info6:"亚洲",info7:"India"},
{name:"艾哈迈达巴德",info1:"Ahmedabad",info2:"AiHaMaiDaBaDe",info3:"AHMDBD",info4:"AMD",info5:"印度",info6:"亚洲",info7:"India"},
{name:"瓦杜达拉",info1:"Vadodara",info2:"WaDuDaLa",info3:"WDDL",info4:"BDQ",info5:"印度",info6:"亚洲",info7:"India"},
{name:"博帕尔",info1:"Bhopal",info2:"BoPaEr",info3:"BPE",info4:"BHO",info5:"印度",info6:"亚洲",info7:"India"},
{name:"库奇",info1:"Kochi",info2:"KuQi",info3:"KQ",info4:"COK",info5:"印度",info6:"亚洲",info7:"India"},
{name:"印多尔",info1:"Indore",info2:"YinDuoEr",info3:"YDE",info4:"IDR",info5:"印度",info6:"亚洲",info7:"India"},
{name:"克久拉霍",info1:"Khajuraho",info2:"KeJiuLaHuo",info3:"KJLH",info4:"HJR",info5:"印度",info6:"亚洲",info7:"India"},
{name:"焦特布尔",info1:"Jodhpur",info2:"JiaoTeBuEr",info3:"JTBE",info4:"JDH",info5:"印度",info6:"亚洲",info7:"India"},
{name:"乌代布尔",info1:"Udaipur",info2:"WuDaiBuEr",info3:"UDBE",info4:"UDR",info5:"印度",info6:"亚洲",info7:"India"},
{name:"斯利那加",info1:"Srinagar",info2:"SiLiNaJia",info3:"SLNJ",info4:"SXR",info5:"印度",info6:"亚洲",info7:"India"},
{name:"巴格多格拉",info1:"Bagdogra",info2:"BaGeDuoGeLa",info3:"BGDGL",info4:"IXB",info5:"印度",info6:"亚洲",info7:"India"},
{name:"古瓦哈蒂",info1:"Guwahati",info2:"GuWaHaDi",info3:"GWHD",info4:"GAU",info5:"印度",info6:"亚洲",info7:"India"},
{name:"芽庄",info1:"Nhatrang",info2:"YaZhuang",info3:"YZ",info4:"NHA",info5:"越南",info6:"亚洲",info7:"Vietnam"},
{name:"达尔文",info1:"Darwin",info2:"DaErWen",info3:"DEW",info4:"DRW",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"海曼岛",info1:"Haymanisland",info2:"HaiManDao",info3:"HMD",info4:"HIS",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"麦夸里港",info1:"Portmacquarie",info2:"MaiKuaLiGang",info3:"MKLG",info4:"PQQ",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"科夫斯港",info1:"Coffsharbour",info2:"KeFuSiGang",info3:"KFSG",info4:"CFS",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"黄金海岸",info1:"Sunshinecoast",info2:"HuangJinHaiAn",info3:"HJHA",info4:"MCY",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"朗赛斯顿",info1:"Launceston",info2:"LangSaiSiDun",info3:"LSSD",info4:"LST",info5:"澳大利亚",info6:"大洋洲",info7:"Australia"},
{name:"纳皮尔",info1:"Napier",info2:"NaPiEr",info3:"NPE",info4:"NPE",info5:"新西兰",info6:"大洋洲",info7:"New Zealand"},
{name:"纳尔逊",info1:"Nelson",info2:"NaErXun",info3:"NEX",info4:"NSN",info5:"新西兰",info6:"大洋洲",info7:"New Zealand"},
{name:"新普里茅斯",info1:"Newplymouth",info2:"XinPuLiMaoSi",info3:"XPLMS",info4:"NPL",info5:"新西兰",info6:"大洋洲",info7:"New Zealand"},
{name:"皇后镇",info1:"Queenstown",info2:"HuangHouZhen",info3:"HHZ",info4:"ZQN",info5:"新西兰",info6:"大洋洲",info7:"New Zealand"}
];

var hotCity=[130,37,342,343,64,68,147,70,346,155,79,393,403,270,363,415,259,284,10];

var strInternational = new Array("ADL","AKL","ALA","AMS","APW","ASB","ATH","ATL","BAK","BCN","BDB","BDL","BER","BHX","BKI","BKK","BNE","BOS","BRU","BWN","CBR","CHC","CJJ","CJU","CLE","CNS","CNX","CPH","CRK","CVG","DAC","DEL","DFW","DUD","DUS","DXB","DYU","EDI","EMD","EWR","FKS","FLL","FNJ","FRA","FRU","FUK","GLT","GMP","GVA","HAJ","TYO","HAM","HAN","HBA","HEL","HIJ","HKD","HKG","HKT","HLZ","HNA","HNL","HSG","HTI","IAH","ICN","IKA","IKT","ISA","ISB","IST","JAX","JED","JIN","JKT","KCH","KHV","KIJ","KIX","KKJ","KMJ","KOJ","KTM","KUL","LAD","LAO","LAS","LAX","LBD","LIM","LIS","LON","LOS","MAD","MAN","MCO","MEL","MEM","MFM","MIL","MKY","MLE","MMJ","MNL","MOW","MQL","MSY","MUC","MWX","NAN","NCL","NGO","NGS","NTL","NRT","NUE","NYC","OIT","OKJ","OOL","ORD","OSA","OSL","OSS","OVB","PAR","PEN","PER","PNH","POM","PPP","PUS","RAR","REP","RGN","RMQ","ROK","ROM","SDJ","SEA","SEL","SGN","SHJ","SIN","SKD","SLC","SPK","SPN","STO","STR","SYD","TAE","TAK","TAS","TBS","TBU","THR","TOY","TPA","TPE","TSV","TYO","VIE","VTE","VVO","WAW","WLG","YNY","YVR","ZRH","VTE","DPS","BPN","MDC","MES","PLM","ALG","CAI","ADD","LAD","COO","FIH","JIB","ACC","LBV","HRE","DLA","ABJ","NBO","KGL","TNR","CAS","JNB","CPT","DUR","KAN","ABV","PHC","DKR","KRT","DAR","TUN","EBB","LUN","KNH","KBL","CMB","BOM","HYD","MAA","CCU","BLR","NAG","PNQ","JAI","PAT","IXR","RPR","ATQ","IXC","IXL","JLR","DUB","TLL","MSQ","SOF","KRK","CGN","LED","MRS","SXB","LYS","NCE","PRG","ZAG","RIX","LUX","BUH","OPO","GOT","BEG","LCA","LJU","AGP","VLC","PSA","VCE","BLQ","KPO","OKA","CTS","FKS","KMQ","KWJ","MYJ","NGS","OKJ","MCT","BAH","DOH","KWI","BEY","RUH","DMM","RIY","SAH","AMM","CNS","OOL","CBR","CHC","DUD","HBA","HLZ","HTI","MKY","NTL","PPP","ROK","TSV","WLG","MQL","ADL","BDB","EMD","GLT","ISA","APW","RAR","TBU","NAN","POM","YTO","YMQ","YOW","YEG","DEN","DFW","LAS","MIA","SAN","SFO","SJC","WAS","GUM","SEA","CLT","CMH","DTT","IND","MKE","MSP","MSY","PHL","RDU","PDX","VTE","DPS","BPN","BPN","MDC","MES","PLM","ALG","CAI","ADD","LAD","COO","FIH","JIB","ACC","LBV","HRE","DLA","ABJ","NBO","KGL","TNR","CAS","JNB","CPT","DUR","KAN","ABV","YLW","YQR","YWG","YXE","PHC","YXS","YYC","DKR","KRT","DAR","TUN","EBB","LUN","KNH","KBL","CMB","BOM","HYD","MAA","CCU","BLR","NAG","PNQ","JAI","PAT","IXR","RPR","ATQ","IXC","IXL","JLR","TLL","MSQ","SOF","KRK","CGN","LED","MRS","SXB","LYS","NCE","ZAG","RIX","LUX","VCE","KPO","OKA","CTS","FKS","KMQ","MYJ","NGS","OKJ","MCT","BAH","DOH","KWI","BEY","RUH","DMM","RIY","SAH","AMM","LGK","KBR","TGG","KUA","USM","LHR","TSE","KBP","CGK","CDG","SVO","JFK","TSA","GLA","NCL","ABZ","BFS","YMM","DAD","MCI","AUS","BNA","MRY","OGG","PHX","SBA","TUS","FAT","ANC","BZN","GEG","SMF","MFR","STS","GDL","CUN","SJD","ZLO","MEX","PVR","MID","MTY","CUL","CCS","GRU","GIG","PBM","PTY","BOG","SCL","EZE","IXJ","LKO","TRV","VNS","CCJ","AMD","BDQ","BHO","COK","IDR","HJR","JDH","UDR","SXR","IXB","GAU","NHA","DRW","HIS","PQQ","CFS","MCY","LST","NPE","NSN","NPL","ZQN");