version: '3'

services:
        web:
               build: .
               command: python3 manage.py runserver 0.0.0.0:8000
               volumes:
                       - ./fabbuild:/code
                       - /home/who/pn:/code/pn
               ports:
                       - 8000:8000
                         
