version: "3"
services:
        web:
                image: tomcat
                ports:
                        - "8080:8080"
                volumes:
                        - ./webapps:/usr/local/tomcat/webapps

