== Java底层知识
```
关于Java,可参看Java核心技术36讲和深入拆解Java虚拟机
```

=== Java 字节码相关
可从几个教程中学习：

* https://dzone.com/articles/introduction-to-java-bytecode[Java Zone: Introduction to Java Bytecode] ，这篇文章图文并茂地向你讲述了 Java 字节码的一些细节，是一篇很不错的入门文章。

* https://www.ibm.com/developerworks/library/it-haggar_bytecode/index.html[IBM DeveloperWorks: Java bytecode] ，虽然这篇文章很老了，但是这篇文章是一篇非常好的讲 Java 字节码的文章。

* https://github.com/jon-bell/bytecode-examples[Java Bytecode and JVMTI Examples]，这是一些使用 http://docs.oracle.com/javase/7/docs/platform/jvmti/jvmti.html[JVM Tool Interface] 操作字节码的比较实用的例子。包括方法调用统计、静态字节码修改、Heap Taggin 和 Heap Walking。

一般来说，我们不使用 JVMTI 操作字节码，而是用一些更好用的库。这里有三个库可以帮你比较容易地做这个事。

* https://wiki.openjdk.java.net/display/CodeTools/asmtools[asmtools] - 用于生产环境的 Java .class 文件开发工具。
* http://bytebuddy.net/[Byte Buddy] - 代码生成库：运行时创建 Class 文件而不需要编译器帮助。
* https://github.com/qmx/jitescript[Jitescript] - 和 https://github.com/headius/bitescript[BiteScript] 类似的字节码生成库。

我们不需要在代码中埋点做统计或监控，可以使用这种技术把我们的监控代码直接以字节码的方式注入到别人的代码中，从而实现对实际程序运行情况进行统计和监控。如果你看过我的《编程范式游记》，你就知道这种技术的威力了，其可以很魔法地把业务逻辑和代码控制分离开来。

要做到这个事，你还需要学习一个叫 Java Agent 的技术。Java Agent 使用的是 “ https://stackoverflow.com/questions/11898566/tutorials-about-javaagents[Java Instrumentation API]”，其主要方法是实现一个叫 `premain()`

的方法（嗯，一个比 `main()` 函数还要超前执行的 main 函数），然后把你的代码编译成一个 jar 文件。

在 JVM 启动时，使用这样的命令行来引入你的 jar 文件：`java -javaagent:yourAwesomeAgent.jar -jar App.jar`

。更为详细的文章可以参看：“ https://www.javacodegeeks.com/2015/09/java-agents.html[Java Code Geeks: Java Agents]”，你还可以看一下这个示例项目： https://github.com/toptal/jvm-monitoring-agent[jvm-monitoring-agent] 或是 https://gist.github.com/EntryPointKR/152f089f6f3884047abcd19d39297c9e[EntryPointKR/Agent.java]。如果想用 ByteBuddy 来玩，你可以看看这篇文章 “ http://www.infoq.com/cn/articles/Easily-Create-Java-Agents-with-ByteBuddy[通过使用 Byte Buddy，便捷地创建 Java Agent]”。如果你想学习如何用 Java Agent 做监控，你可以看一下这个项目 http://www.stagemonitor.org/[Stage Monitor]。

=== JVM 相关
JVM 的规格说明书，这里放一个 Java 8 的， https://docs.oracle.com/javase/specs/jvms/se8/jvms8.pdf[The Java Virtual Machine Specification Java SE 8 Edition] 。对于规格说明书的阅读，我认为是系统了解 JVM 规范的最佳文档，这个文档可以让你对于搞不清楚或是诡异的问题恍然大悟。关于中文翻译，有人在 GitHub 上开了个 Repo - “ https://github.com/waylau/java-virtual-machine-specification[java-virtual-machine-specification]”。

另外，也推荐一下 https://shipilev.net/jvm-anatomy-park/[JVM Anatomy Park] JVM 解剖公园，这是一个系列的文章，每篇文章都不长，但是都很精彩，带你一点一点地把 JVM 中的一些技术解开。

学习 Java 底层原理还有 Java 的内存模型，官方文章是 http://www.jcp.org/en/jsr/detail?id=133[JSR 133]。还有马里兰大学的威廉 · 皮尤（William Pugh）教授收集的和 Java 内存模型相关的文献 - http://www.cs.umd.edu/~pugh/java/memoryModel/[The Java Memory Model] ，你可以前往浏览。

对于内存方面，道格 · 利（Doug Lea）有两篇文章也是很有价值的。

* http://gee.cs.oswego.edu/dl/jmm/cookbook.html[The JSR-133 Cookbook for Compiler Writers]，解释了怎样实现 Java 内存模型，特别是在考虑到多处理器（或多核）系统的情况下，多线程和读写屏障的实现。

* http://gee.cs.oswego.edu/dl/html/j9mm.html[Using JDK 9 Memory Order Modes]，讲了怎样通过 VarHandle 来使用 plain、opaque、release/acquire 和 volatile 四种共享内存的访问模式，并剖析了底层的原理。

垃圾回收机制也是需要好好学习的，在这里推荐一本书 《The Garbage Collection Handbook》，这本书非常全面地介绍了垃圾收集的原理、设计和算法。但是这本书也是相当难啃的。中文翻译[垃圾回收算法手册》翻译得很一般。

当然，更多的人可能只需要知道怎么调优垃圾回收， 那么推荐读读 http://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/[Garbage Collection Tuning Guide] ，它是 Hotspot Java 虚拟机的垃圾回收调优指南，对你很有帮助。

https://gist.github.com/djspiewak/464c11307cabc80171c90397d4ec34ef[Quick Tips for Fast Code on the JVM] 也是一篇很不错的文章，里面有写出更快的 Java 代码的几个小提示，值得一读。





