== 编程语言
需要学习 C、C++ 和 Java 这三个工业级的编程语言。为什么说它们是工业级的呢？主要是，C 和 C++ 语言规范都由 ISO 标准化过，而且都有工业界厂商组成的标准化委员会来制定工业标准。次要原因是，它们已经在业界应用于许多重要的生产环境中。

荐学习 Go 语言。这门语言已经 10 多年了，其已成为云计算领域事实上的标准语言，尤其是在 Docker/Kubernetes 等项目中。参看： https://coolshell.cn/articles/18190.html[Go 语言、Docker 和新技术]一文。

=== 理论学科
需要学习算法、数据结构、网络模型、计算机原理等计算机科学专业需要学习的知识。为什么要学好这些理论上的知识呢？

*   其一，这些理论知识可以说是计算机科学这门学科最精华的知识了。说得大一点，这些是人类智慧的精华。你只要想成为高手，这些东西是你必需要掌握和学习的。

*   其二，当你在解决一些很复杂或是很难的问题时，这些基础理论知识可以帮到你很多。我过去这 20 年从这些基础理论知识中受益匪浅。

*   其三，这些理论知识的思维方式可以让你有触类旁通，一通百通的感觉。虽然知识比较难啃，但啃过以后，你将获益终生。

你千万不要觉得在你的日常工作或是生活当中根本用不上，学了也白学，这样的思维方式千万不要有，因为这是平庸的思维方式。如果你想等我用到了再学也不晚，那么你有必要看一下这篇文章 https://coolshell.cn/articles/4235.html[程序员的荒谬之言还是至理名言？]。

=== 系统知识
系统知识是理论知识的工程实践，这里面有很多很多的细节。比如像 Unix/Linux、TCP/IP、C10K 挑战等这样专业的系统知识。这些知识是你能不能把理论应用到实际项目当中，能不能搞定实际问题的重要知识。

当你在编程的时候，如何和系统进行交互或是获取操作系统的资源，如何进行通讯，当系统出了性能问题，当系统出了故障等，你有大量需要落地的事需要处理和解决。这个时候，这些系统知识就会变得尤为关键和重要了。

这些东西，你可以认为是计算机世界的物理世界，上层无论怎么玩，无论是 Java NIO，还是 Nginx，还是 Node.js，它们都逃脱不掉最下层的限制。所以，你要好好学习这方面的知识。

=== Java
****
入门级::
《Java 核心技术：卷 1 基础知识》 C -> C++ -> Java 整条线融汇贯通、《Spring 实战》、《Spring Boot 实战》
提升级::
《Effective Java》third Edition；Google Guava 库，是 Effective Java 这本书中的那些经验的实践代表。
--
《Java 并发编程实战》-- 书中从并发性和线程安全性的基本概念出发，介绍了如何使用类库提供的基本并发构建块，用于避免并发危险、构造线程安全的类及验证线程安全的规则，如何将小的线程安全类组合成更大的线程安全类，如何利用线程来提高并发应用程序的吞吐量，如何识别可并行执行的任务，如何提高单线程子系统的响应性，如何确保并发程序执行预期任务，如何提高并发代码的性能和可伸缩性等内容。最后介绍了一些高级主题，如显式锁、原子变量、非阻塞算法以及如何开发自定义的同步工具类。
--
《Java 性能权威指南》--如何优化 Java 的性能。通过学习这本书，你可以比较大程度地提升性能测试的效果。其中包括：使用 JDK 中自带的工具收集 Java 应用的性能数据，理解 JIT 编译器的优缺点，调优 JVM 垃圾收集器以减少对程序的影响，学习管理堆内存和 JVM 原生内存的方法，了解如何最大程度地优化 Java 线程及同步的性能，等等。想了解更多的底层细节，那么，你有必要去读一下《深入理解 Java 虚拟机》。
--
《Java 编程思想》--信息密度比较大。对于想学好 Java 的程序员来说，这是一本必读的书。
--
《精通 Spring 4.x》--分析原理，尤其是针对前面提到的 Spring 技术，应用与原理都讲得很透彻，IOC 和 AOP 也分析得很棒。

学 Java 一定要学面向对象的设计模式，这里就只有一本经典的书《设计模式》。如果你觉得有点儿难度了，那么可以看一下《[Head First 设计模式]》。学习面向对象的设计模式时，你不要迷失在那 23 个设计模式中，你一定要明白这两个原则：

*   **Program to an ‘interface’, not an 'implementation’**

    **   使用者不需要知道数据类型、结构、算法的细节。
    **   使用者不需要知道实现细节，只需要知道提供的接口。
    **   利于抽象、封装，动态绑定，多态。符合面向对象的特质和理念。
*   **Favor ‘object composition’ over 'class inheritance’**

    **   继承需要给子类暴露一些父类的设计和实现细节。
    **   父类实现的改变会造成子类也需要改变。
    **   我们以为继承主要是为了代码重用，但实际上在子类中需要重新实现很多父类的方法。
    **   继承更多的应该是为了多态。

****

=== C/C++ 语言
****
C 语言之父 Dennis M. Ritchie 和著名科学家 Brian W. Kernighan 合作的圣经级的教科书《C 程序设计语言》。注意，这本书是 C 语言原作者写的，其 C 语言的标准不是我们平时常说的 ANSI 标准，而是原作者的标准，又被叫作 K&R C。但是这本书很轻薄，也简洁，不枯燥。

《C 语言程序设计现代方法》。有人说，这本书配合之前的 https://en.wikipedia.org/wiki/The_C_Programming_Language[The C Programming Language] 那本书简真是无敌。我想说，这本书更实用，也够厚，完整覆盖了 C99 标准，习题的质量和水准也比较高。更好的是，探讨了现代编译器的实现，以及和 C++ 的兼容，还揭穿了各种古老的 C 语言的神话和信条…… 是相当相当干的一本学习 C 语言的书。

千万不要看谭浩强的 C 语言的书。

《C 陷阱与缺陷》这本书，你会发现，这里面的坑不是一般大。

C++ 是目前世界上范式最多的语言了，其做得最好的范式就是 "泛型编程"，这在静态语言中，是绝对地划时代的一个事**。

所以，你有必要学习一下 C + + ，看看 C+ +  是如何解决 C 语言中的各种问题的。你可以先看看我的这篇文章  https://coolshell.cn/articles/7992.html[C + +  的坑真的多吗？] ，有个基本认识。下面推荐几本 C + + 的书：

*   《C + + Primer 中文版》，这本书是久负盛名的 C+ +  经典教程。书是有点厚，前面 1/3 讲 C 语言，后面讲 C+ + 。C+ +  的知识点实在是太多了，而且又有点晦涩。但是你主要就看几个点，一个是面向对象的多态，一个是模板和重载操作符，以及一些 STL 的东西。看看 C+ +  是怎么玩泛型和函数式编程的。

*   如果你想继续研究，你需要看另外两本更为经典的书《Effective C + + 》和《More Effective C + + 》。 这两本书不厚，但是我读了 10 多年，每过一段时间再读一下，就会发现有更多的收获。这两本书的内容会随着你经历的丰富而变得丰富，这也是对我影响最大的两本书，其中影响最大的不是书中的那些 C++ 的东西，而是作者的思维方式和不断求真的精神，这真是太赞了。

*   学习 C/C + + 都是需要好好了解一下编译器到底干了什么事的。就像 Java 需要了解 JVM 一样，所以，这里还有一本非常非常难啃的书你可以挑战一下《深度探索 C + + 对象模型》。这本书是非常之经典的，看完后，C + + 对你来说就再也没有什么秘密可言。  https://coolshell.cn/articles/12165.html[C + + 虚函数表解析] ，还有 https://coolshell.cn/articles/12176.html[C + + 对象内存布局]属于这个范畴。

*   还有 C + + 的作者 Bjarne Stroustrup 写的  http://www.stroustrup.com/bs_faq.html[C+ + FAQ] 、 http://www.stroustrup.com/bsfaqcn.html[中文版]，也是非常值得一读的。
****

=== Go
****
首推  https://gobyexample.com/[Go by Example] 作为你的入门教程。然后， https://go101.org/article/101.html 也是一个很不错的在线电子书。如果你想看纸书的话，《The Go Programming Language》 一书在豆瓣上有 9.2 分，但是国内没有卖的。（当然，我以前也写过两篇入门的供你参考  https://coolshell.cn/articles/8460.html[GO 语言简介（上）- 语法] 和  https://coolshell.cn/articles/8489.html[GO 语言简介（下）- 特性]。

另外，Go 语言官方的  https://golang.org/doc/effective_go.html[Effective Go] 是必读的，这篇文章告诉你如何更好地使用 Go 语言，以及 Go 语言中的一些原理。

Go 语言最突出之处是并发编程，Unix 老牌黑客罗勃 · 派克（Rob Pike）在 Google I/O 上的两个分享，可以让你学习到一些并发编程的模式。

*   Go Concurrency Patterns（  https://talks.golang.org/2012/concurrency.slide[幻灯片]和 https://www.youtube.com/watch?v=f6kdp27TYZs[演讲视频]）。
*   Advanced Go Concurrency Patterns（ https://talks.golang.org/2013/advconc.slide[幻灯片]、 https://youtu.be/QDDwwePbDtw[演讲视频]）。

然后，Go 在 GitHub 的 wiki 上有好多不错的学习资源，你可以从中学习到多。比如：

*   [Go 精华文章列表](https://github.com/golang/go/wiki/Articles)。
*   [Go 相关博客列表](https://github.com/golang/go/wiki/Blogs)。
*   [Go Talks](https://github.com/golang/go/wiki/GoTalks)。

此外，还有个内容丰富的 Go 资源列表  https://github.com/avelino/awesome-go[Awesome Go]，推荐看看。
****
















