== 正式入门
=== 编程技能
如何有效地快速提高自己的编程能力 http://blog.thefirehoseproject.com/posts/learn-to-code-and-be-self-reliant/[The Key To Accelerating Your Coding Skills]

* **编程技巧方面**
****
《代码大全》。这本书好多年没有更新了，其中有一些内容可能有点过时，但还是一本非常好的书，有点厚，你不需要马上就看完。在你的编程路上，这本书可以陪你走很久，因为当你有更多的编程经验时，走过更多的坑后，再把这本书拿出来看看，你会有更多的体会。
**** 
* **编程语言方面**
**** 
java::
    《Java 核心技术（卷 1）》、《Spring in action》、Spring的IoC和AOP
**** 
        
* **操作系统**
**** 
《鸟哥的 Linux 私房菜》
**** 
    
* **网络协议**
**** 
系统地了解一下 HTTP 协议，请到  https://developer.mozilla.org/zh-CN/docs/Web/[MDN HTTP] 阅读。你需要知道 HTTP 协议的几个关键点：1）HTTP 头，2）HTTP 的请求方法，3）HTTP 的返回码。还有，HTTP 的 Cookie、缓存、会话，以及链接管理，等等
**** 
    
* **数据库设计**
**** 
慕课网的一个在线课程– https://www.imooc.com/learn/117[数据库设计的那些事],要搞清楚数据的那几个范式，还有 SQL 语句的一些用法。推荐学习开源的 MySQL。你可以看官方文档，也可以看《MySQL 必知必会》、《高性能MySQL（第3版）》
****     

* **前端方面**
****    
JavaScript 相关的 https://jquery.com/[jQuery]，另一个是和 CSS 相关的 https://getbootstrap.com/[Bootstrap]，学习这两个东西都不复杂，直接上其官网看文档就好了。最重要的是，你要学习一下如何使用 JavaScript Ajax 请求后端的 API 接口。这里，你需要学习一下，JavaScript 的 Promise 模式。 http://es6.ruanyifeng.com/#docs/promise[阮一峰的 ES6 ]。当然，你 Google 一下，也可以找到一堆学习资料。
****
  
* **字符编码方面**
****
在你处理中文时有时会发现有乱码出现，此时需要了解 ASCII 和 Unicode 这样的字符编码。这里推荐一篇文章 - http://www.imkevinyang.com/2010/06/%E5%85%B3%E4%BA%8E%E5%AD%97%E7%AC%A6%E7%BC%96%E7%A0%81%EF%BC%8C%E4%BD%A0%E6%89%80%E9%9C%80%E8%A6%81%E7%9F%A5%E9%81%93%E7%9A%84.html[关于字符编码，你所需要知道的（ASCII,Unicode,Utf-8,GB2312…] 或是英文文章 http://www.developerknowhow.com/1091/the-history-of-character-encoding[The history of Character Encoding] 
以及 https://en.wikipedia.org/wiki/Character_encoding[Wikipedia - Character encoding]。
还有 GitHub 上的这两个 Awesome 仓库： https://github.com/jagracey/Awesome-Unicode[Awesome Unicode] 和 https://github.com/Codepoints/awesome-codepoints[Awesome Code Points]。
****

=== 编程工具

* **编程的 IDE**
****
传统一点的，你可以使用 http://www.runoob.com/eclipse/eclipse-tutorial.html[ Eclipse教程]。当然，我推荐你使用  https://www.gitbook.com/book/dancon/intellij-idea/details[Intellij IDEA教程]。这两个工具都可以开发各种语言，但是主要用在 Java。*如果你想玩得更时髦一些的话，使用 Visual Studio Code 也不错，这个工具潜力十足*，用其开发 Python、JavaScript、Java、Go、C 和 C++ 都能得心应手 https://www.gitbook.com/book/jeasonstudio/vscode-cn-doc/details[教程] 。
****

* **版本管理工具**
****
版本管理工具是非常重要的编程工具。传统的有 P4、 SVN、CVS 等，但都会被 Git 取代，所以，你就只用学习 Git 就好了。学习 Git 的教程网上有很多，这里我推荐非常系统的 https://git-scm.com/book/zh/v2/[Pro Git 第二版] （如果你觉得 Pro Git 比较枯燥的话，备选 https://backlog.com/git-tutorial/cn/[猴子都能懂的 Git 入门]），然后你要学会使用 GitHub。关于一些 Git 环境安装和准备以及 GitHub 使用，你可以自行 Google（比如：这篇  https://github.com/JiapengLi/GitTutorial[GitHub and Git 图文教程] 或是这篇  https://www.jianshu.com/p/1b65ed31da97[Git 图文教程及详解]）。
****

* **调试前端程序**
****
你需要学会使用 Chrome 调试前端程序，Google 一下会有很多文章，你可以看看     http://www.igeekbar.com/igeekbar/post/156.htm[超完整的 Chrome 浏览器客户端调试大全]。
****

* **数据库设计工具**
****
你需要学会使用 MySQL WorkBench，这个工具很容易使用。相关的手册，你可以看一下 https://dev.mysql.com/doc/refman/5.7/en/[官方文档]。
****

=== Oracle补充
****
TODO
****
