# Version: 0.0.1
FROM ubuntu:latest
MAINTAINER WHOYIING "375416934@QQ.COM"
RUN apt-get update
Run apt-get install -y nginx
Run echo 'Hi, I am in your container'  /usr/share/nginx/html/index.html
EXPOSE 80
