# Version: 0.0.1
FROM ubunt:latest
MAINTAINER WHOYIING "375416934@QQ.COM"
RUN apt-get install update
Run apt-get install -y nginx
Run echo 'Hi, I am in your container' > /usr/share/nginx/html/index.html
EXPOSE 80



